// FIX: Import React to make React.ComponentType available.
import React from 'react';
import { Translations, Plan } from './types';
import { FileText, Gavel, Briefcase, Shield, Scale, BookOpen, Building2, Home, Copyright, Handshake, Fingerprint, Banknote, Landmark, Users, Ship, Plane, PersonStanding, Percent, Leaf, Swords, Library, UserCheck, ShieldCheck, Gem, Factory, DollarSign, Recycle, HeartHandshake, Plus, Trash2, Edit, Loader2, Play, Workflow, Archive, Server, ClipboardCheck, HeartCrack, UserX, KeyRound, ScanEye, FlaskConical, Wand2, Search, Film, MapPin, Image, Ratio, ScanLine, AudioLines, Volume2, BrainCircuit, Video, ArrowLeft, ArrowRight, File, User, CreditCard, Star, CheckCircle2, Cog, LayoutDashboard, BarChart, LifeBuoy, MessageSquare, Send, Inbox, Tag, Sparkles, Sliders, Settings2, Bell, LayoutTemplate, Sun, Moon, Globe, LogOut, ChevronDown, Info, AlertTriangle, CheckCircle, PlusSquare, X, Coins, Gift, Ban, RefreshCw, Activity, Filter, MoreVertical, ChevronRight, Copy, Check, Printer, ZoomIn, ZoomOut, LayoutGrid, Maximize2, Minimize2 } from 'lucide-react';

export const ADMIN_EMAIL = 'binawad1@gmail.com';

// ⚠️ هام جداً: هذا الملف هو كود الواجهة الأمامية (Frontend).
// يجب استخدام "المفتاح القابل للنشر" (Publishable Key) الذي يبدأ بـ 'pk_live_...'.
// ❌ لا تستخدم مفتاح 'rk_live_...' (Restricted Key) أو 'sk_live_...' (Secret Key) هنا أبداً.
// المفاتيح التي تبدأ بـ rk_ أو sk_ ستتسبب في تعليق صفحة الدفع ولن تعمل.

// IMPORTANT: Use your Stripe LIVE Publishable Key here.
// It MUST start with 'pk_live_'. Do NOT use 'rk_live_' or 'sk_live_'.
export const STRIPE_PUBLISHABLE_KEY = 'pk_live_51MHLcOIYFzPtizLNW6GO3QlnhsgSqNz1oTaBnKaFrg0xcoNej1mGufkKgKIP8Vb1CIrXBbHD5tfVVTQo62mgAEmK00dmJQ';

// FIX: Export iconMap for use in components
export const iconMap: { [key: string]: React.ComponentType<any> } = {
    FileText, Gavel, Briefcase, Shield, Scale, BookOpen, Building2, Home, Copyright, Handshake, Fingerprint, Banknote, Landmark, Users, Ship, Plane, PersonStanding, Percent, Leaf, Swords, Library, UserCheck, ShieldCheck, Gem, Factory, DollarSign, Recycle, HeartHandshake, Plus, Trash2, Edit, Loader2, Play, Workflow, Archive, Server, ClipboardCheck, HeartCrack, UserX, KeyRound, ScanEye, FlaskConical, Wand2, Search, Film, MapPin, Image, Ratio, ScanLine, AudioLines, Volume2, BrainCircuit, Video, ArrowLeft, ArrowRight, File, User, CreditCard, Star, CheckCircle2, Cog, LayoutDashboard, BarChart, LifeBuoy, MessageSquare, Send, Inbox, Tag, Sparkles, Sliders, Settings2, Bell, LayoutTemplate, Sun, Moon, Globe, LogOut, ChevronDown, Info, AlertTriangle, CheckCircle, PlusSquare, X, Coins, Gift, Ban, RefreshCw, Activity, Filter, MoreVertical, ChevronRight, Copy, Check, Printer, ZoomIn, ZoomOut, LayoutGrid, Maximize2, Minimize2
};

// FIX: Export iconNames for use in AdminPage AI generator
export const iconNames = Object.keys(iconMap);

// FIX: Export translations for use in LanguageContext
export const translations: Translations = {
    // General
    appName: { en: 'The Smart Assistant', ar: 'المساعد الذكي' },
    appSubtitle: { en: 'For Law and Legal Consultations', ar: 'للمحاماة والاستشارات القانونية' },
    home: { en: 'Home', ar: 'الرئيسية' },
    services: { en: 'Services', ar: 'الخدمات' },
    support: { en: 'Support', ar: 'الدعم الفني' },
    login: { en: 'Login', ar: 'تسجيل الدخول' },
    logout: { en: 'Logout', ar: 'تسجيل الخروج' },
    signup: { en: 'Sign Up', ar: 'إنشاء حساب' },
    myProfile: { en: 'My Profile', ar: 'ملفي الشخصي' },
    loading: { en: 'Loading...', ar: 'جاري التحميل...' },
    cancel: { en: 'Cancel', ar: 'إلغاء' },
    save: { en: 'Save', ar: 'حفظ' },
    edit: { en: 'Edit', ar: 'تعديل' },
    delete: { en: 'Delete', ar: 'حذف' },
    add: { en: 'Add', ar: 'إضافة' },
    email: { en: 'Email Address', ar: 'البريد الإلكتروني' },
    password: { en: 'Password', ar: 'كلمة المرور' },
    confirmPassword: { en: 'Confirm Password', ar: 'تأكيد كلمة المرور' },
    or: { en: 'OR', ar: 'أو' },
    arabic: { en: 'Arabic', ar: 'العربية' },
    english: { en: 'English', ar: 'الإنجليزية' },
    
    // AuthModal
    signInWithGoogle: { en: 'Sign in with Google', ar: 'الدخول بواسطة جوجل' },
    passwordsDontMatch: { en: 'Passwords do not match.', ar: 'كلمات المرور غير متطابقة.' },
    dontHaveAccount: { en: "Don't have an account?", ar: 'ليس لديك حساب؟' },
    alreadyHaveAccount: { en: 'Already have an account?', ar: 'لديك حساب بالفعل؟' },
    
    // Service Card
    runService: { en: 'Run', ar: 'تشغيل' },
    
    // Service Execution Modal
    modelIsBusyRetrying: { en: 'Model is busy. Retrying... (Attempt ${attempt}/${maxRetries})', ar: 'النموذج مشغول. جاري إعادة المحاولة... (محاولة ${attempt}/${maxRetries})' },
    serviceSavedError: { en: 'Error executing service', ar: 'خطأ في تنفيذ الخدمة' },
    uploadFile: { en: 'Upload a file', ar: 'رفع ملف' },
    noFileSelected: { en: 'No file selected', ar: 'لم يتم اختيار ملف' },
    executeTask: { en: 'Execute', ar: 'تنفيذ' },
    outputLanguage: { en: 'Output Language', ar: 'لغة المخرجات' },
    stop: { en: 'Stop', ar: 'إيقاف' },
    listen: { en: 'Listen', ar: 'استماع' },
    copied: { en: 'Copied!', ar: 'تم النسخ!' },
    copy: { en: 'Copy', ar: 'نسخ' },
    print: { en: 'Print', ar: 'طباعة' },
    results: { en: 'Results', ar: 'النتائج' },
    resultPlaceholder: { en: 'The generated result will appear here.', ar: 'ستظهر النتائج التي تم إنشاؤها هنا.' },
    
    // Landing Page
    heroTitleMain: { en: 'The Future of Legal Work', ar: 'مستقبل العمل القانوني' },
    heroTitleHighlight: { en: 'Powered by AI', ar: 'مدعوم بالذكاء الاصطناعي' },
    heroSubtitle: { en: 'Leverage artificial intelligence for legal research, document drafting, and case analysis to enhance efficiency and accuracy.', ar: 'استفد من الذكاء الاصطناعي في الأبحاث القانونية وصياغة المستندات وتحليل القضايا لتعزيز الكفاءة والدقة.' },
    featuresTitle: { en: 'Our Key Features', ar: 'أبرز مميزاتنا' },
    goToDashboard: { en: 'Go to Dashboard', ar: 'الذهاب إلى لوحة التحكم' },
    startFreeTrial: { en: 'Start Free Trial', ar: 'ابدأ تجربتك المجانية' },
    locationAwarenessMessage: { en: 'Get AI-powered legal insights tailored to your jurisdiction. Your location provides context for more accurate, locally-relevant answers.', ar: 'احصل على رؤى قانونية مدعومة بالذكاء الاصطناعي ومخصصة لمنطقتك. يوفر موقعك سياقًا للحصول على إجابات أكثر دقة وملاءمة محليًا.' },
    pricingTitle: { en: 'Flexible Pricing Plans', ar: 'خطط أسعار مرنة' },
    pricingSubtitle: { en: 'Choose the plan that fits your needs and scale as you grow.', ar: 'اختر الخطة التي تناسب احتياجاتك وتوسع مع نموك.' },
    mostPopular: { en: 'Most Popular', ar: 'الأكثر شيوعاً' },
    tokens: { en: 'Tokens', ar: 'رمز' },
    choosePlan: { en: 'Choose Plan', ar: 'اختر الخطة' },
    finalCtaTitle: { en: 'Ready to Transform Your Legal Practice?', ar: 'هل أنت مستعد لتغيير ممارستك القانونية؟' },
    finalCtaSubtitle: { en: 'Join today and experience the power of AI in the legal field.', ar: 'انضم اليوم واختبر قوة الذكاء الاصطناعي في المجال القانوني.' },
    signUpForFree: { en: 'Sign Up for Free', ar: 'سجل مجانا' },
    feature1Title: { en: 'Instant Document Analysis', ar: 'تحليل فوري للمستندات' },
    feature1Desc: { en: 'Upload your legal documents and get summaries, key point extractions, and risk assessments in seconds.', ar: 'ارفع مستنداتك القانونية واحصل على ملخصات واستخراج النقاط الرئيسية وتقييمات المخاطر في ثوانٍ.' },
    feature2Title: { en: 'Smart Legal Research', ar: 'بحث قانوني ذكي' },
    feature2Desc: { en: 'Ask complex legal questions in natural language and receive well-reasoned, cited answers based on current laws.', ar: 'اطرح أسئلة قانونية معقدة بلغة طبيعية واحصل على إجابات مدعومة بالأدلة ومبنية على القوانين الحالية.' },
    feature3Title: { en: 'Automated Drafting', ar: 'صياغة آلية' },
    feature3Desc: { en: 'Generate first drafts of memos, contracts, and pleadings, saving you hours of tedious work.', ar: 'أنشئ مسودات أولية للمذكرات والعقود والمرافعات، مما يوفر لك ساعات من العمل الشاق.' },
    feature4Title: { en: 'Legal Risk Assessment', ar: 'تقييم المخاطر القانونية' },
    feature4Desc: { en: 'Identify potential liabilities in contracts or business strategies before they become problems.', ar: 'تحديد الالتزامات المحتملة في العقود أو استراتيجيات العمل قبل أن تصبح مشاكل.' },
    feature5Title: { en: 'Strategic Case Planning', ar: 'تخطيط استراتيجية القضايا' },
    feature5Desc: { en: 'Develop data-driven legal strategies by analyzing case facts and predicting potential outcomes.', ar: 'تطوير استراتيجيات قانونية مبنية على البيانات من خلال تحليل وقائع القضايا وتوقع النتائج المحتملة.' },
    feature6Title: { en: 'Regulatory Compliance', ar: 'الامتثال التنظيمي' },
    feature6Desc: { en: 'Stay up-to-date and compliant with ever-changing local and international regulations.', ar: 'ابق على اطلاع دائم ومتوافق مع اللوائح المحلية والدولية المتغيرة باستمرار.' },
    feature7Title: { en: 'Client Communication', ar: 'التواصل مع العملاء' },
    feature7Desc: { en: 'Generate professional, clear, and empathetic responses to client inquiries.', ar: 'إنشاء ردود احترافية وواضحة ومتعاطفة على استفسارات العملاء.' },
    feature8Title: { en: 'Legal Translation', ar: 'الترجمة القانونية' },
    feature8Desc: { en: 'Get accurate, context-aware translations of legal documents and terminology.', ar: 'احصل على ترجمات دقيقة ومدركة للسياق للمستندات والمصطلحات القانونية.' },
    feature9Title: { en: 'Smart Archiving', ar: 'الأرشفة الذكية' },
    feature9Desc: { en: 'Organize and search your case files and legal knowledge base with intelligent tagging and summaries.', ar: 'نظم وابحث في ملفات قضاياك وقاعدة معارفك القانونية باستخدام العلامات والملخصات الذكية.' },

    // Dashboard
    searchServicePlaceholder: { en: 'Search for a service...', ar: 'ابحث عن خدمة...' },
    allCategories: { en: 'All', ar: 'الكل' },
    favorites: { en: 'Favorites', ar: 'المفضلة' },
    litigationAndPleadings: { en: 'Litigation & Pleadings', ar: 'التقاضي والمذكرات' },
    specializedConsultations: { en: 'Specialized Consultations', ar: 'الاستشارات التخصصية' },
    investigationsAndCriminal: { en: 'Investigations & Criminal', ar: 'التحقيقات والجنائي' },
    corporateAndCompliance: { en: 'Corporate & Compliance', ar: 'الشركات والامتثال' },
    creativeServices: { en: 'Creative Services', ar: 'الخدمات الإبداعية' },
    noServicesFound: { en: 'No services found for the current filter.', ar: 'لم يتم العثور على خدمات للتصنيف الحالي.' },
    outOfTokens: { en: 'You have run out of tokens. Please upgrade your plan to continue.', ar: 'لقد نفدت الرموز الخاصة بك. يرجى ترقية خطتك للمتابعة.' },
    poweredByAI: { en: 'Powered by AI', ar: 'مدعوم بالذكاء الاصطناعي' },
    typeYourRequest: { en: 'Type your request here for a quick answer...', ar: 'اكتب طلبك هنا للحصول على إجابة سريعة...' },
    generatingResponse: { en: 'Generating response...', ar: 'جاري إنشاء الرد...' },
    
    // Subscriptions
    planDescription: { en: 'Unlock more features and increase your token limit with our premium plans.', ar: 'افتح المزيد من الميزات وزد من حد الرموز الخاص بك مع خططنا المميزة.' },
    fetchPlansError: { en: 'Failed to load subscription plans.', ar: 'فشل في تحميل خطط الاشتراك.' },
    stripeKeysNotConfigured: { en: 'Stripe keys are not configured correctly.', ar: 'مفاتيح Stripe غير مهيأة بشكل صحيح.' },
    paymentError: { en: 'An error occurred during payment processing.', ar: 'حدث خطأ أثناء معالجة الدفع.' },
    redirectingToPayment: { en: 'Redirecting...', ar: 'جاري التوجيه...' },
    
    // Profile
    overview: { en: 'Manage your profile, subscription, and security settings.', ar: 'إدارة ملفك الشخصي واشتراكك وإعدادات الأمان.' },
    profileUpdatedSuccess: { en: 'Profile updated successfully!', ar: 'تم تحديث الملف الشخصي بنجاح!' },
    profileUpdatedError: { en: 'Failed to update profile.', ar: 'فشل تحديث الملف الشخصي.' },
    reAuthRequired: { en: 'Authentication Required', ar: 'المصادقة مطلوبة' },
    reAuthMessage: { en: 'For your security, please enter your current password to continue.', ar: 'لأمانك، يرجى إدخال كلمة المرور الحالية للمتابعة.' },
    currentPassword: { en: 'Current Password', ar: 'كلمة المرور الحالية' },
    authenticate: { en: 'Authenticate', ar: 'توثيق' },
    authenticationError: { en: 'Authentication failed. Please check your password.', ar: 'فشلت المصادقة. يرجى التحقق من كلمة المرور الخاصة بك.' },
    emailUpdateSuccess: { en: 'A verification link has been sent to your new email address.', ar: 'تم إرسال رابط تحقق إلى عنوان بريدك الإلكتروني الجديد.' },
    emailUpdateError: { en: 'Failed to update email.', ar: 'فشل تحديث البريد الإلكتروني.' },
    passwordUpdateSuccess: { en: 'Password updated successfully!', ar: 'تم تحديث كلمة المرور بنجاح!' },
    passwordUpdateError: { en: 'Failed to update password.', ar: 'فشل تحديث كلمة المرور.' },
    portalError: { en: 'Could not redirect to customer portal.', ar: 'لا يمكن التوجيه إلى بوابة العملاء.' },
    addTokens: { en: 'Add More Tokens', ar: 'إضافة المزيد من الرموز' },
    subscription: { en: 'Subscription', ar: 'الاشتراك' },
    noSubscription: { en: 'No Active Plan', ar: 'لا توجد خطة نشطة' },
    manageSubscription: { en: 'Manage Subscription', ar: 'إدارة الاشتراك' },
    upgradeNow: { en: 'Upgrade Now', ar: 'الترقية الآن' },
    canceledOn: { en: 'Canceled on', ar: 'تم الإلغاء في' },
    renewsOn: { en: 'Renews on', ar: 'يتجدد في' },
    editProfile: { en: 'Personal Information', ar: 'المعلومات الشخصية' },
    fullName: { en: 'Full Name', ar: 'الاسم الكامل' },
    location: { en: 'Location / Jurisdiction', ar: 'الموقع / الاختصاص القضائي' },
    locationPlaceholder: { en: 'e.g., Riyadh, Saudi Arabia', ar: 'مثال: الرياض، المملكة العربية السعودية' },
    saveChanges: { en: 'Save Changes', ar: 'حفظ التغييرات' },
    security: { en: 'Security Settings', ar: 'إعدادات الأمان' },
    changeEmail: { en: 'Change Email Address', ar: 'تغيير عنوان البريد الإلكتروني' },
    newEmail: { en: 'New Email Address', ar: 'البريد الإلكتروني الجديد' },
    updateEmail: { en: 'Update Email', ar: 'تحديث البريد' },
    changePassword: { en: 'Change Password', ar: 'تغيير كلمة المرور' },
    newPassword: { en: 'New Password', ar: 'كلمة المرور الجديدة' },
    confirmNewPassword: { en: 'Confirm New Password', ar: 'تأكيد كلمة المرور الجديدة' },
    updatePassword: { en: 'Update Password', ar: 'تحديث كلمة المرور' },

    // Footer
    disclaimerTitle: { en: 'Disclaimer', ar: 'إخلاء مسؤولية' },
    disclaimerText: { en: 'This tool is powered by artificial intelligence and is for informational purposes only. It does not constitute legal advice. Always consult with a qualified legal professional for advice on your specific situation.', ar: 'هذه الأداة مدعومة بالذكاء الاصطناعي وهي للأغراض المعلوماتية فقط. لا تشكل نصيحة قانونية. استشر دائمًا محترفًا قانونيًا مؤهلاً للحصول على مشورة بشأن وضعك المحدد.' },
    copyrightText: { en: '© 2024 The Smart Assistant. All Rights Reserved.', ar: '© 2024 المساعد الذكي. جميع الحقوق محفوظة.' },
    technicalSupport: { en: 'Technical Support', ar: 'الدعم الفني' },
    
    // Chat Widget
    aiAssistant: { en: 'AI Assistant', ar: 'المساعد الذكي' },
    typeMessage: { en: 'Type your message...', ar: 'اكتب رسالتك...' },
    chatWithAI: { en: 'Chat with AI', ar: 'تحدث مع المساعد' },

    // Admin
    adminPanel: { en: 'Admin Panel', ar: 'لوحة التحكم' },
    userManagement: { en: 'User Management', ar: 'إدارة المستخدمين' },
    manageServices: { en: 'Service Management', ar: 'إدارة الخدمات' },
    subscriptionManagement: { en: 'Subscription Management', ar: 'إدارة الاشتراكات' },
    planManagement: { en: 'Plan Management', ar: 'إدارة الخطط' },
    siteSettings: { en: 'Site Settings', ar: 'إعدادات الموقع' },
    landingPage: { en: 'Landing Page', ar: 'الصفحة الرئيسية' },
    marketing: { en: 'Marketing Pixels', ar: 'بكسلات التسويق' },
    notifications: { en: 'Notifications', ar: 'الإشعارات' },
    totalUsers: { en: 'Total Users', ar: 'إجمالي المستخدمين' },
    activeSubscribers: { en: 'Active Subscribers', ar: 'المشتركون النشطون' },
    tokenBalance: { en: 'Total Token Balance', ar: 'إجمالي رصيد الرموز' },
    tokensUsed: { en: 'Total Tokens Used', ar: 'إجمالي الرموز المستخدمة' },
    role: { en: 'Role', ar: 'الدور' },
    status: { en: 'Status', ar: 'الحالة' },
    used: { en: 'Used', ar: 'المستخدم' },
    dateJoined: { en: 'Date Joined', ar: 'تاريخ الانضمام' },
    actions: { en: 'Actions', ar: 'الإجراءات' },
    adminRole: { en: 'Admin', ar: 'مدير' },
    userRole: { en: 'User', ar: 'مستخدم' },
    active: { en: 'Active', ar: 'نشط' },
    disabled: { en: 'Disabled', ar: 'معطل' },
    inactive: { en: 'Inactive', ar: 'غير نشط' },
    enable: { en: 'Enable', ar: 'تفعيل' },
    disable: { en: 'Disable', ar: 'تعطيل' },
    deleteUserConfirm: { en: 'Are you sure you want to delete this user? This action cannot be undone.', ar: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.' },
    userDeletedSuccess: { en: 'User deleted successfully.', ar: 'تم حذف المستخدم بنجاح.' },
    userDeletedError: { en: 'Failed to delete user.', ar: 'فشل حذف المستخدم.' },
    enableUserConfirm: { en: 'Are you sure you want to enable this user account?', ar: 'هل أنت متأكد من رغبتك في تفعيل حساب هذا المستخدم؟' },
    disableUserConfirm: { en: 'Are you sure you want to disable this user account?', ar: 'هل أنت متأكد من رغبتك في تعطيل حساب هذا المستخدم؟' },
    userUpdatedSuccess: { en: 'User updated successfully.', ar: 'تم تحديث المستخدم بنجاح.' },
    userUpdatedError: { en: 'Failed to update user.', ar: 'فشل تحديث المستخدم.' },
    fetchUsersIndexError: { en: 'Error fetching data. A Firestore index is likely required. Check the console for a link to create it.', ar: 'خطأ في جلب البيانات. من المحتمل أن يكون فهرس Firestore مطلوبًا. تحقق من وحدة التحكم للحصول على رابط لإنشائه.' },
    fetchUsersError: { en: 'Failed to load users.', ar: 'فشل في تحميل المستخدمين.' },
    noUsersFound: { en: 'No users found.', ar: 'لم يتم العثور على مستخدمين.' },
    grantSubscription: { en: 'Grant Manual Subscription', ar: 'منح اشتراك يدوي' },
    selectUser: { en: 'Select a user', ar: 'اختر مستخدم' },
    validTokenAmount: { en: 'Please enter a valid token amount.', ar: 'الرجاء إدخال كمية رموز صالحة.' },
    validDuration: { en: 'Please enter a valid duration in days.', ar: 'الرجاء إدخال مدة صالحة بالأيام.' },
    grantSuccess: { en: 'Subscription and tokens granted successfully.', ar: 'تم منح الاشتراك والرموز بنجاح.' },
    grantError: { en: 'Failed to grant subscription', ar: 'فشل منح الاشتراك' },
    selectPlan: { en: 'Select a plan', ar: 'اختر خطة' },
    customPlan: { en: 'Custom / Manual', ar: 'مخصص / يدوي' },
    tokenAmount: { en: 'Token Amount', ar: 'كمية الرموز' },
    durationDays: { en: 'Duration (Days)', ar: 'المدة (أيام)' },
    grant: { en: 'Grant', ar: 'منح' },
    tokensAddedSuccess: { en: 'Tokens added successfully.', ar: 'تمت إضافة الرموز بنجاح.' },
    plan: { en: 'Plan', ar: 'الخطة' },
    endsOn: { en: 'Ends on', ar: 'ينتهي في' },
    type: { en: 'Type', ar: 'النوع' },
    revoke: { en: 'Revoke', ar: 'إلغاء' },
    revokeConfirm: { en: 'Are you sure you want to revoke this manual subscription? This will delete the subscription record but will not affect the user\'s token balance.', ar: 'هل أنت متأكد من رغبتك في إلغاء هذا الاشتراك اليدوي؟ سيؤدي هذا إلى حذف سجل الاشتراك ولكنه لن يؤثر على رصيد رموز المستخدم.' },
    revokeSuccess: { en: 'Subscription revoked successfully.', ar: 'تم إلغاء الاشتراك بنجاح.' },
    revokeError: { en: 'Failed to revoke subscription.', ar: 'فشل إلغاء الاشتراك.' },
    manageInStripe: { en: 'Manage in Stripe', ar: 'الإدارة عبر Stripe' },
    noActiveSubscription: { en: 'No users with active subscriptions found.', ar: 'لم يتم العثور على مستخدمين لديهم اشتراكات نشطة.' },
    fetchSubsError: { en: 'Failed to load subscriptions.', ar: 'فشل في تحميل الاشتراكات.' },
    generateWithAI: { en: 'Generate Service with AI', ar: 'إنشاء خدمة بالذكاء الاصطناعي' },
    aiGeneratorDescription: { en: 'Describe the legal service you want to create (e.g., "Draft a non-disclosure agreement"), and the AI will generate the complete configuration for you.', ar: 'صف الخدمة القانونية التي تريد إنشاءها (على سبيل المثال، "صياغة اتفاقية عدم إفصاح")، وسيقوم الذكاء الاصطناعي بإنشاء التكوين الكامل لك.' },
    serviceNamePlaceholder: { en: 'e.g., "Draft a rental contract"', ar: 'مثال: "صياغة عقد إيجار"' },
    generate: { en: 'Generate', ar: 'إنشاء' },
    enterServiceName: { en: 'Please enter a service name to generate.', ar: 'الرجاء إدخال اسم خدمة لإنشائها.' },
    generateServiceError: { en: 'Failed to generate service with AI. Please check the console for details.', ar: 'فشل إنشاء الخدمة بالذكاء الاصطناعي. يرجى مراجعة وحدة التحكم للحصول على التفاصيل.' },
    serviceDetails: { en: 'New Service Details', ar: 'تفاصيل الخدمة الجديدة' },
    editService: { en: 'Edit Service', ar: 'تعديل الخدمة' },
    serviceIdPlaceholder: { en: 'Service ID (e.g., rental-contract-draft)', ar: 'معرّف الخدمة (مثال: rental-contract-draft)' },
    geminiModel: { en: 'Gemini Model', ar: 'نموذج Gemini' },
    titleEnPlaceholder: { en: 'Title (English)', ar: 'العنوان (إنجليزي)' },
    titleArPlaceholder: { en: 'Title (Arabic)', ar: 'العنوان (عربي)' },
    descriptionEnPlaceholder: { en: 'Description (English)', ar: 'الوصف (إنجليزي)' },
    descriptionArPlaceholder: { en: 'Description (Arabic)', ar: 'الوصف (عربي)' },
    category: { en: 'Category', ar: 'الفئة' },
    subCategory: { en: 'Sub-Category', ar: 'الفئة الفرعية' },
    subCategoryEnPlaceholder: { en: 'Sub-Category (English)', ar: 'الفئة الفرعية (إنجليزي)' },
    subCategoryArPlaceholder: { en: 'Sub-Category (Arabic)', ar: 'الفئة الفرعية (عربي)' },
    icon: { en: 'Icon', ar: 'أيقونة' },
    formInputs: { en: 'Form Inputs', ar: 'حقول النموذج' },
    inputNamePlaceholder: { en: 'Input Name (e.g., client_name)', ar: 'اسم الحقل (مثال: client_name)' },
    labelEnPlaceholder: { en: 'Label (English)', ar: 'التسمية (إنجليزي)' },
    labelArPlaceholder: { en: 'Label (Arabic)', ar: 'التسمية (عربي)' },
    options: { en: 'Options', ar: 'الخيارات' },
    addOption: { en: 'Add Option', ar: 'إضافة خيار' },
    addFormInput: { en: 'Add Form Input', ar: 'إضافة حقل نموذج' },
    saveService: { en: 'Save Service', ar: 'حفظ الخدمة' },
    serviceIdRequired: { en: 'Service ID is required.', ar: 'معرّف الخدمة مطلوب.' },
    serviceSavedSuccess: { en: 'Service saved successfully.', ar: 'تم حفظ الخدمة بنجاح.' },
    serviceSavedErrorAdmin: { en: 'Error saving service.', ar: 'خطأ في حفظ الخدمة.' },
    existingServices: { en: 'Existing Services', ar: 'الخدمات الحالية' },
    deleteSelected: { en: 'Delete Selected', ar: 'حذف المحدد' },
    deleteSelectedConfirm: { en: 'Are you sure you want to delete the {count} selected services?', ar: 'هل أنت متأكد من رغبتك في حذف {count} من الخدمات المحددة؟' },
    serviceName: { en: 'Service Name', ar: 'اسم الخدمة' },
    usage: { en: 'Usage', ar: 'الاستخدام' },
    run: { en: 'Run', ar: 'تشغيل' },
    deleteConfirm: { en: 'Are you sure you want to delete this item? This action cannot be undone.', ar: 'هل أنت متأكد من رغبتك في حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.' },
    serviceDeletedSuccess: { en: 'Service(s) deleted successfully.', ar: 'تم حذف الخدمة (الخدمات) بنجاح.' },
    serviceDeletedError: { en: 'Failed to delete service(s).', ar: 'فشل حذف الخدمة (الخدمات).' },
    fetchServicesError: { en: 'Failed to load services.', ar: 'فشل في تحميل الخدمات.' },
    addNewPlan: { en: 'Add New Plan', ar: 'إضافة خطة جديدة' },
    editPlan: { en: 'Edit Plan', ar: 'تعديل الخطة' },
    planId: { en: 'Plan ID (e.g., standard-monthly)', ar: 'معرف الخطة (مثال: standard-monthly)' },
    priceId: { en: 'Stripe Price ID', ar: 'معرف السعر في Stripe' },
    planTitleEn: { en: 'Title (EN)', ar: 'العنوان (EN)' },
    planTitleAr: { en: 'Title (AR)', ar: 'العنوان (AR)' },
    planPriceEn: { en: 'Price (EN, e.g., "$19/mo")', ar: 'السعر (EN, مثال: "$19/mo")' },
    planPriceAr: { en: 'Price (AR, e.g., "١٩$ / شهر")', ar: 'السعر (AR, مثال: "١٩$ / شهر")' },
    planTokens: { en: 'Tokens Included', ar: 'الرموز المضمنة' },
    isPopular: { en: 'Mark as "Most Popular"', ar: 'تمييز كـ "الأكثر شيوعًا"' },
    planFeatures: { en: 'Plan Features', ar: 'ميزات الخطة' },
    featureEn: { en: 'Feature (EN)', ar: 'الميزة (EN)' },
    featureAr: { en: 'Feature (AR)', ar: 'الميزة (AR)' },
    addFeature: { en: 'Add Feature', ar: 'إضافة ميزة' },
    savePlan: { en: 'Save Plan', ar: 'حفظ الخطة' },
    planSavedSuccess: { en: 'Plan saved successfully.', ar: 'تم حفظ الخطة بنجاح.' },
    planSavedError: { en: 'Failed to save plan.', ar: 'فشل حفظ الخطة.' },
    deletePlanConfirm: { en: 'Are you sure you want to delete this plan?', ar: 'هل أنت متأكد أنك تريد حذف هذه الخطة؟' },
    planDeletedSuccess: { en: 'Plan deleted successfully.', ar: 'تم حذف الخطة بنجاح.' },
    planDeletedError: { en: 'Failed to delete plan.', ar: 'فشل حذف الخطة.' },
    planStatusUpdated: { en: 'Plan status updated.', ar: 'تم تحديث حالة الخطة.' },
    planStatusUpdateError: { en: 'Failed to update plan status.', ar: 'فشل تحديث حالة الخطة.' },
    deactivate: { en: 'Deactivate', ar: 'إلغاء التنشيط' },
    activate: { en: 'Activate', ar: 'تنشيط' },
    customPageActive: { en: 'Custom Page Active', ar: 'صفحة مخصصة نشطة' },
    defaultPageActive: { en: 'Default Page Active', ar: 'صفحة افتراضية نشطة' },
    resetToDefault: { en: 'Reset to Default', ar: 'إعادة للوضع الافتراضي' },
    resetLandingConfirm: { en: 'Are you sure you want to reset the landing page to its default content? The AI-generated content will be lost.', ar: 'هل أنت متأكد من رغبتك في إعادة تعيين الصفحة الرئيسية إلى محتواها الافتراضي؟ سيتم فقدان المحتوى الذي تم إنشاؤه بواسطة الذكاء الاصطناعي.' },
    landingResetSuccess: { en: 'Landing page has been reset to default.', ar: 'تمت إعادة تعيين الصفحة الرئيسية إلى الوضع الافتراضي.' },
    generateWithAIConfig: { en: 'Generate with AI', ar: 'إنشاء باستخدام الذكاء الاصطناعي' },
    enterTopic: { en: 'Enter a topic for the landing page (e.g., "AI for Corporate Law")', ar: 'أدخل موضوعًا للصفحة الرئيسية (مثال: "الذكاء الاصطناعي لقانون الشركات")' },
    landingGeneratedSuccess: { en: 'New landing page configuration has been generated and saved!', ar: 'تم إنشاء وحفظ تكوين الصفحة الرئيسية الجديد بنجاح!' },
    landingGenerateFailed: { en: 'Failed to generate landing page content.', ar: 'فشل إنشاء محتوى الصفحة الرئيسية.' },
    siteNameEn: { en: 'Site Name (EN)', ar: 'اسم الموقع (EN)' },
    siteNameAr: { en: 'Site Name (AR)', ar: 'اسم الموقع (AR)' },
    siteSubtitleEn: { en: 'Site Subtitle (EN)', ar: 'وصف الموقع (EN)' },
    siteSubtitleAr: { en: 'Site Subtitle (AR)', ar: 'وصف الموقع (AR)' },
    metaDescriptionEn: { en: 'Meta Description (EN)', ar: 'وصف الميتا (EN)' },
    metaDescriptionAr: { en: 'Meta Description (AR)', ar: 'وصف الميتا (AR)' },
    seoKeywordsEn: { en: 'SEO Keywords (EN, comma-separated)', ar: 'كلمات SEO (EN، مفصولة بفواصل)' },
    seoKeywordsAr: { en: 'SEO Keywords (AR, comma-separated)', ar: 'كلمات SEO (AR، مفصولة بفواصل)' },
    logo: { en: 'Logo', ar: 'الشعار' },
    favicon: { en: 'Favicon', ar: 'أيقونة الموقع' },
    enableMaintenance: { en: 'Enable Maintenance Mode', ar: 'تفعيل وضع الصيانة' },
    saveSettings: { en: 'Save Settings', ar: 'حفظ الإعدادات' },
    settingsSavedSuccess: { en: 'Settings saved successfully.', ar: 'تم حفظ الإعدادات بنجاح.' },
    settingsSavedError: { en: 'Failed to save settings.', ar: 'فشل حفظ الإعدادات.' },
    adPixels: { en: 'Ad Pixels & Tracking IDs', ar: 'بكسلات الإعلانات ومعرفات التتبع' },
    adPixelsDesc: { en: 'Add your tracking IDs to enable marketing analytics.', ar: 'أضف معرفات التتبع الخاصة بك لتمكين تحليلات التسويق.' },
    googleTagId: { en: 'Google Tag ID', ar: 'معرف علامة جوجل' },
    facebookPixelId: { en: 'Facebook Pixel ID', ar: 'معرف بكسل فيسبوك' },
    snapchatPixelId: { en: 'Snapchat Pixel ID', ar: 'معرف بكسل سناب شات' },
    tiktokPixelId: { en: 'TikTok Pixel ID', ar: 'معرف بكسل تيك توك' },
    openTicket: { en: 'Open New Ticket', ar: 'فتح تذكرة جديدة' },
    submitTicket: { en: 'Submit Ticket', ar: 'إرسال التذكرة' },
    noTickets: { en: 'You have no support tickets.', ar: 'ليس لديك تذاكر دعم.' },
    ticketSubject: { en: 'Subject', ar: 'الموضوع' },
    ticketType: { en: 'Ticket Type', ar: 'نوع التذكرة' },
    message: { en: 'Message', ar: 'الرسالة' },
    typeReply: { en: 'Type your reply...', ar: 'اكتب ردك...' },
    selectTicket: { en: 'Select a ticket to view the conversation.', ar: 'اختر تذكرة لعرض المحادثة.' },
    technicalSupportType: { en: 'Technical Support', ar: 'دعم فني' },
    additionalService: { en: 'Request Additional Service', ar: 'طلب خدمة إضافية' },
    specialSubscription: { en: 'Special Subscription Inquiry', ar: 'استفسار عن اشتراك خاص' },
    open: { en: 'Open', ar: 'مفتوحة' },
    closed: { en: 'Closed', ar: 'مغلقة' },
    answered: { en: 'Answered', ar: 'تم الرد' },
    createNotification: { en: 'Create Notification', ar: 'إنشاء إشعار' },
    titleEn: { en: 'Title (EN)', ar: 'العنوان (EN)' },
    titleAr: { en: 'Title (AR)', ar: 'العنوان (AR)' },
    messageEn: { en: 'Message (EN)', ar: 'الرسالة (EN)' },
    messageAr: { en: 'Message (AR)', ar: 'الرسالة (AR)' },
    notificationType: { en: 'Notification Type', ar: 'نوع الإشعار' },
    info: { en: 'Info', ar: 'معلومات' },
    success: { en: 'Success', ar: 'نجاح' },
    warning: { en: 'Warning', ar: 'تحذير' },
    alert: { en: 'Alert', ar: 'تنبيه' },
    fillAllFields: { en: 'Please fill all required fields.', ar: 'يرجى ملء جميع الحقول المطلوبة.' },
    notificationCreated: { en: 'Notification created successfully.', ar: 'تم إنشاء الإشعار بنجاح.' },
    notificationFailed: { en: 'Failed to create notification.', ar: 'فشل إنشاء الإشعار.' },
    areYouSure: { en: 'Are you sure?', ar: 'هل أنت متأكد؟' },
    noNotificationsFound: { en: 'No notifications found.', ar: 'لم يتم العثور على إشعارات.' },

    // Maintenance Mode
    maintenanceMode: { en: 'Site Under Maintenance', ar: 'الموقع تحت الصيانة' },
    maintenanceMessage: { en: 'We are currently performing scheduled maintenance. Please check back later.', ar: 'نقوم حاليًا بإجراء صيانة مجدولة. يرجى العودة لاحقًا.' },
};