// FIX: Import React to make React.ComponentType available.
import React from 'react';
import { Translations, Plan } from './types';
import { FileText, Gavel, Briefcase, Shield, Scale, BookOpen, Building2, Home, Copyright, Handshake, Fingerprint, Banknote, Landmark, Users, Ship, Plane, PersonStanding, Percent, Leaf, Swords, Library, UserCheck, ShieldCheck, Gem, Factory, DollarSign, Recycle, HeartHandshake, Plus, Trash2, Edit, Loader2, Play, Workflow, Archive, Server, ClipboardCheck, HeartCrack, UserX, KeyRound, ScanEye, FlaskConical, Wand2, Search, Film, MapPin, Image, Ratio, ScanLine, AudioLines, Volume2, BrainCircuit, Video, ArrowLeft, ArrowRight, File, User, CreditCard, Star, CheckCircle2, Cog, LayoutDashboard, BarChart, LifeBuoy, MessageSquare, Send, Inbox, Tag, Sparkles, Sliders, Settings2, Bell, LayoutTemplate, Sun, Moon, Globe, LogOut, ChevronDown, Info, AlertTriangle, CheckCircle, PlusSquare, X, Coins, Gift, Ban, RefreshCw, Activity, Filter, MoreVertical, ChevronRight, Copy, Check, Printer, ZoomIn, ZoomOut, LayoutGrid, Maximize2, Minimize2 } from 'lucide-react';

export const ADMIN_EMAIL = 'binawad1@gmail.com';

// ⚠️ هام جداً: هذا الملف هو كود الواجهة الأمامية (Frontend).
// يجب استخدام "المفتاح القابل للنشر" (Publishable Key) الذي يبدأ بـ 'pk_live_...'.
// ❌ لا تستخدم مفتاح 'rk_live_...' (Restricted Key) أو 'sk_live_...' (Secret Key) هنا أبداً.
// المفاتيح التي تبدأ بـ rk_ أو sk_ ستتسبب في تعليق صفحة الدفع ولن تعمل.

// IMPORTANT: Use your Stripe LIVE Publishable Key here.
// It MUST start with 'pk_live_'. Do NOT use 'rk_live_' or 'sk_live_'.
export const STRIPE_PUBLISHABLE_KEY = 'pk_live_51MHLcOIYFzPtizLNW6GO3QlnhsgSqNz1oTaBnKaFrg0xcoNej1mGufkKgKIP8Vb1CIrXBbHD5tfVVTQo62mgAEmK00dmJQ';

// FIX: Export iconMap for use in components
export const iconMap: { [key: string]: React.ComponentType<any> } = {
    FileText, Gavel, Briefcase, Shield, Scale, BookOpen, Building2, Home, Copyright, Handshake, Fingerprint, Banknote, Landmark, Users, Ship, Plane, PersonStanding, Percent, Leaf, Swords, Library, UserCheck, ShieldCheck, Gem, Factory, DollarSign, Recycle, HeartHandshake, Plus, Trash2, Edit, Loader2, Play, Workflow, Archive, Server, ClipboardCheck, HeartCrack, UserX, KeyRound, ScanEye, FlaskConical, Wand2, Search, Film, MapPin, Image, Ratio, ScanLine, AudioLines, Volume2, BrainCircuit, Video, ArrowLeft, ArrowRight, File, User, CreditCard, Star, CheckCircle2, Cog, LayoutDashboard, BarChart, LifeBuoy, MessageSquare, Send, Inbox, Tag, Sparkles, Sliders, Settings2, Bell, LayoutTemplate, Sun, Moon, Globe, LogOut, ChevronDown, Info, AlertTriangle, CheckCircle, PlusSquare, X, Coins, Gift, Ban, RefreshCw, Activity, Filter, MoreVertical, ChevronRight, Copy, Check, Printer, ZoomIn, ZoomOut, LayoutGrid, Maximize2, Minimize2
};

// FIX: Export iconNames for use in AdminPage AI generator
export const iconNames = Object.keys(iconMap);

// FIX: Export translations for use in LanguageContext
export const translations: Translations = {
    // General
    appName: { en: 'The Smart Assistant', ar: 'المساعد الذكي' },
    appSubtitle: { en: 'For Law and Legal Consultations', ar: 'للمحاماة والاستشارات القانونية' },
    home: { en: 'Home', ar: 'الرئيسية' },
    services: { en: 'Services', ar: 'الخدمات' },
    support: { en: 'Support', ar: 'الدعم الفني' },
    login: { en: 'Login', ar: 'تسجيل الدخول' },
    logout: { en: 'Logout', ar: 'تسجيل الخروج' },
    signup: { en: 'Sign Up', ar: 'إنشاء حساب' },
    myProfile: { en: 'My Profile', ar: 'ملفي الشخصي' },
    loading: { en: 'Loading...', ar: 'جاري التحميل...' },
    cancel: { en: 'Cancel', ar: 'إلغاء' },
    save: { en: 'Save', ar: 'حفظ' },
    edit: { en: 'Edit', ar: 'تعديل' },
    delete: { en: 'Delete', ar: 'حذف' },
    add: { en: 'Add', ar: 'إضافة' },
    email: { en: 'Email Address', ar: 'البريد الإلكتروني' },
    password: { en: 'Password', ar: 'كلمة المرور' },
    confirmPassword: { en: 'Confirm Password', ar: 'تأكيد كلمة المرور' },
    or: { en: 'OR', ar: 'أو' },
    arabic: { en: 'Arabic', ar: 'العربية' },
    english: { en: 'English', ar: 'الإنجليزية' },
    
    // AuthModal
    signInWithGoogle: { en: 'Sign in with Google', ar: 'الدخول بواسطة جوجل' },
    passwordsDontMatch: { en: 'Passwords do not match.', ar: 'كلمات المرور غير متطابقة.' },
    dontHaveAccount: { en: "Don't have an account?", ar: 'ليس لديك حساب؟' },
    alreadyHaveAccount: { en: 'Already have an account?', ar: 'لديك حساب بالفعل؟' },
    
    // Service Card
    runService: { en: 'Run', ar: 'تشغيل' },
    
    // Service Execution Modal
    modelIsBusyRetrying: { en: 'Model is busy. Retrying... (Attempt ${attempt}/${maxRetries})', ar: 'النموذج مشغول. جاري إعادة المحاولة... (محاولة ${attempt}/${maxRetries})' },
    serviceSavedError: { en: 'Error executing service', ar: 'خطأ في تنفيذ الخدمة' },
    uploadFile: { en: 'Upload a file', ar: 'رفع ملف' },
    noFileSelected: { en: 'No file selected', ar: 'لم يتم اختيار ملف' },
    executeTask: { en: 'Execute', ar: 'تنفيذ' },
    outputLanguage: { en: 'Output Language', ar: 'لغة المخرجات' },
    stop: { en: 'Stop', ar: 'إيقاف' },
    listen: { en: 'Listen', ar: 'استماع' },
    copied: { en: 'Copied!', ar: 'تم النسخ!' },
    copy: { en: 'Copy', ar: 'نسخ' },
    print: { en: 'Print', ar: 'طباعة' },
    results: { en: 'Results', ar: 'النتائج' },
    resultPlaceholder: { en: 'The generated result will appear here.', ar: 'ستظهر النتائج التي تم إنشاؤها هنا.' },
    generatingResponse: { en: 'Generating response...', ar: 'جاري إنشاء الرد...' },
    outOfTokens: { en: 'You are out of tokens. Please upgrade your plan.', ar: 'لقد نفدت الرموز لديك. يرجى ترقية خطتك.' },

    // Landing Page
    heroTitleMain: { en: 'The Future of Legal Work', ar: 'مستقبل العمل القانوني' },
    heroTitleHighlight: { en: 'Powered by AI', ar: 'مدعوم بالذكاء الاصطناعي' },
    heroSubtitle: { en: 'Leverage artificial intelligence for legal research, document drafting, and case analysis to enhance efficiency and accuracy.', ar: 'استفد من الذكاء الاصطناعي في الأبحاث القانونية وصياغة المستندات وتحليل القضايا لتعزيز الكفاءة والدقة.' },
    featuresTitle: { en: 'Our Key Features', ar: 'أبرز مميزاتنا' },
    goToDashboard: { en: 'Go to Dashboard', ar: 'الذهاب إلى لوحة التحكم' },
    startFreeTrial: { en: 'Start Free Trial', ar: 'ابدأ تجربتك المجانية' },
    locationAwarenessMessage: { en: 'Get AI-powered legal insights tailored to your jurisdiction. Your location provides context for more accurate, locally-relevant answers.', ar: 'احصل على رؤى قانونية مدعومة بالذكاء الاصطناعي ومخصصة لمنطقتك. يوفر موقعك سياقًا للحصول على إجابات أكثر دقة وملاءمة محليًا.' },
    pricingTitle: { en: 'Flexible Pricing Plans', ar: 'خطط أسعار مرنة' },
    pricingSubtitle: { en: 'Choose the plan that fits your needs and scale as you grow.', ar: 'اختر الخطة التي تناسب احتياجاتك وتوسع مع نموك.' },
    mostPopular: { en: 'Most Popular', ar: 'الأكثر شيوعاً' },
    tokens: { en: 'Tokens', ar: 'رمز' },
    choosePlan: { en: 'Choose Plan', ar: 'اختر الخطة' },
    finalCtaTitle: { en: 'Ready to Transform Your Legal Practice?', ar: 'هل أنت مستعد لتغيير ممارستك القانونية؟' },
    finalCtaSubtitle: { en: 'Join today and experience the power of AI in the legal field.', ar: 'انضم اليوم واختبر قوة الذكاء الاصطناعي في المجال القانوني.' },
    signUpForFree: { en: 'Sign Up for Free', ar: 'سجل مجانا' },
    feature1Title: { en: 'Instant Document Analysis', ar: 'تحليل فوري للمستندات' },
    feature1Desc: { en: 'Upload your legal documents and get summaries, key point extractions, and risk assessments in seconds.', ar: 'ارفع مستنداتك القانونية واحصل على ملخصات واستخراج النقاط الرئيسية وتقييمات المخاطر في ثوانٍ.' },
    feature2Title: { en: 'Smart Legal Research', ar: 'بحث قانوني ذكي' },
    feature2Desc: { en: 'Ask complex legal questions in natural language and receive well-reasoned, cited answers based on current laws.', ar: 'اطرح أسئلة قانونية معقدة بلغة طبيعية واحصل على إجابات مدعومة بالأدلة ومبنية على القوانين الحالية.' },
    // FIX: The translations object was truncated and had syntax errors. Completed the missing feature translations and added missing category translations.
    feature3Title: { en: 'Automated Drafting', ar: 'صياغة آلية' },
    feature3Desc: { en: 'Generate first drafts of memos, contracts, and legal correspondence with AI assistance.', ar: 'أنشئ مسودات أولية للمذكرات والعقود والمراسلات القانونية بمساعدة الذكاء الاصطناعي.' },
    feature4Title: { en: 'Legal Risk Assessment', ar: 'تقييم المخاطر القانونية' },
    feature4Desc: { en: 'Identify potential legal risks in contracts or business plans and get mitigation strategies.', ar: 'تحديد المخاطر القانونية المحتملة في العقود أو خطط العمل والحصول على استراتيجيات للتخفيف منها.' },
    feature5Title: { en: 'Strategic Case Planning', ar: 'تخطيط استراتيجية القضايا' },
    feature5Desc: { en: 'Develop data-driven strategies by analyzing case law and predicting opponent tactics.', ar: 'تطوير استراتيجيات مبنية على البيانات من خلال تحليل السوابق القضائية وتوقع تكتيكات الخصم.' },
    feature6Title: { en: 'Regulatory Compliance', ar: 'الامتثال التنظيمي' },
    feature6Desc: { en: 'Stay up-to-date and compliant with ever-changing local and international regulations.', ar: 'ابق على اطلاع دائم ومتوافق مع اللوائح المحلية والدولية المتغيرة باستمرار.' },
    feature7Title: { en: 'Client Communication', ar: 'التواصل مع العملاء' },
    feature7Desc: { en: 'Generate professional, clear, and empathetic responses to client inquiries and updates.', ar: 'إنشاء ردود احترافية وواضحة ومتعاطفة على استفسارات العملاء وتحديثاتهم.' },
    feature8Title: { en: 'Legal Translation', ar: 'الترجمة القانونية' },
    feature8Desc: { en: 'Translate legal documents between languages with high accuracy for legal terminology.', ar: 'ترجمة المستندات القانونية بين اللغات بدقة عالية للمصطلحات القانونية.' },
    feature9Title: { en: 'Smart Archiving', ar: 'الأرشفة الذكية' },
    feature9Desc: { en: 'Organize and search your legal knowledge base, case files, and documents efficiently.', ar: 'نظم وابحث في قاعدة معارفك القانونية وملفات القضايا والمستندات بكفاءة.' },

    // Service Categories
    litigationAndPleadings: { en: 'Litigation and Pleadings', ar: 'الدعاوى والمرافعات' },
    specializedConsultations: { en: 'Specialized Consultations', ar: 'الاستشارات المتخصصة' },
    investigationsAndCriminal: { en: 'Investigations and Criminal', ar: 'التحقيقات والجنائي' },
    creativeServices: { en: 'Creative Services', ar: 'الخدمات الإبداعية' },
    corporateAndCompliance: { en: 'Corporate & Compliance', ar: 'الشركات والامتثال' },
    allCategories: { en: 'All Categories', ar: 'جميع الأقسام' },
    favorites: { en: 'Favorites', ar: 'المفضلة' },

    // Dashboard Page
    searchServicePlaceholder: { en: 'Search for a service...', ar: 'ابحث عن خدمة...' },
    typeYourRequest: { en: 'Type your request here...', ar: 'اكتب طلبك هنا...' },
    poweredByAI: { en: 'Powered by AI', ar: 'مدعوم بالذكاء الاصطناعي' },

    // Admin Page - General
    adminPanel: { en: 'Admin Panel', ar: 'لوحة التحكم' },
    userManagement: { en: 'User Management', ar: 'إدارة المستخدمين' },
    manageServices: { en: 'Manage Services', ar: 'إدارة الخدمات' },
    subscriptionManagement: { en: 'Subscription Management', ar: 'إدارة الاشتراكات' },
    planManagement: { en: 'Plan Management', ar: 'إدارة الخطط' },
    siteSettings: { en: 'Site Settings', ar: 'إعدادات الموقع' },
    marketing: { en: 'Marketing', ar: 'التسويق' },
    notifications: { en: 'Notifications', ar: 'الإشعارات' },
    actions: { en: 'Actions', ar: 'الإجراءات' },
    status: { en: 'Status', ar: 'الحالة' },
    active: { en: 'Active', ar: 'نشط' },
    inactive: { en: 'Inactive', ar: 'غير نشط' },
    disabled: { en: 'Disabled', ar: 'معطل' },
    enable: { en: 'Enable', ar: 'تفعيل' },
    disable: { en: 'Disable', ar: 'تعطيل' },

    // Admin - User Management
    totalUsers: { en: 'Total Users', ar: 'إجمالي المستخدمين' },
    activeSubscribers: { en: 'Active Subscribers', ar: 'المشتركون النشطون' },
    tokenBalance: { en: 'Token Balance', ar: 'رصيد الرموز' },
    tokensUsed: { en: 'Tokens Used', ar: 'الرموز المستخدمة' },
    role: { en: 'Role', ar: 'الدور' },
    used: { en: 'Used', ar: 'المستخدم' },
    dateJoined: { en: 'Date Joined', ar: 'تاريخ الانضمام' },
    adminRole: { en: 'Admin', ar: 'مدير' },
    userRole: { en: 'User', ar: 'مستخدم' },
    grantSubscription: { en: 'Grant Subscription', ar: 'منح اشتراك' },
    addTokens: { en: 'Add Tokens', ar: 'إضافة رموز' },
    noUsersFound: { en: 'No users found.', ar: 'لم يتم العثور على مستخدمين.' },
    fetchUsersIndexError: { en: 'Error fetching users. A Firestore index is likely required. Please check the console for a link to create it.', ar: 'خطأ في جلب المستخدمين. من المحتمل أن يكون فهرس Firestore مطلوبًا. يرجى مراجعة وحدة التحكم للحصول على رابط لإنشائه.' },
    fetchUsersError: { en: 'Failed to load users.', ar: 'فشل تحميل المستخدمين.' },
    enableUserConfirm: { en: 'Are you sure you want to enable this user?', ar: 'هل أنت متأكد من رغبتك في تفعيل هذا المستخدم؟' },
    disableUserConfirm: { en: 'Are you sure you want to disable this user?', ar: 'هل أنت متأكد من رغبتك في تعطيل هذا المستخدم؟' },
    userUpdatedSuccess: { en: 'User status updated successfully.', ar: 'تم تحديث حالة المستخدم بنجاح.' },
    userUpdatedError: { en: 'Failed to update user status.', ar: 'فشل تحديث حالة المستخدم.' },
    deleteUserConfirm: { en: 'Are you sure you want to permanently delete this user and all their data? This action cannot be undone.', ar: 'هل أنت متأكد من رغبتك في حذف هذا المستخدم وجميع بياناته بشكل دائم؟ لا يمكن التراجع عن هذا الإجراء.' },
    userDeletedSuccess: { en: 'User deleted successfully.', ar: 'تم حذف المستخدم بنجاح.' },
    userDeletedError: { en: 'Failed to delete user.', ar: 'فشل حذف المستخدم.' },
    tokensAddedSuccess: { en: 'Tokens added successfully.', ar: 'تمت إضافة الرموز بنجاح.' },
    selectUser: { en: 'Select User', ar: 'اختر مستخدم' },
    selectPlan: { en: 'Select Plan', ar: 'اختر خطة' },
    tokenAmount: { en: 'Token Amount', ar: 'كمية الرموز' },
    durationDays: { en: 'Duration (Days)', ar: 'المدة (أيام)' },
    grant: { en: 'Grant', ar: 'منح' },
    grantSuccess: { en: 'Subscription and tokens granted successfully.', ar: 'تم منح الاشتراك والرموز بنجاح.' },
    grantError: { en: 'Failed to grant subscription.', ar: 'فشل منح الاشتراك.' },
    validTokenAmount: { en: 'Please enter a valid, positive token amount.', ar: 'الرجاء إدخال كمية رموز صالحة وموجبة.' },
    validDuration: { en: 'Please enter a valid duration in days.', ar: 'الرجاء إدخال مدة صالحة بالأيام.' },

    // Admin - Service Management
    generateWithAI: { en: 'Generate Service with AI', ar: 'إنشاء خدمة بالذكاء الاصطناعي' },
    aiGeneratorDescription: { en: 'Describe a new service (e.g., "Draft a commercial lease contract") and the AI will generate the full configuration for you.', ar: 'صف خدمة جديدة (مثال: "صياغة عقد إيجار تجاري") وسيقوم الذكاء الاصطناعي بإنشاء الإعدادات الكاملة لك.' },
    serviceNamePlaceholder: { en: 'Enter service name, e.g., "Review an employment contract"', ar: 'أدخل اسم الخدمة، مثال: "مراجعة عقد عمل"' },
    generate: { en: 'Generate', ar: 'إنشاء' },
    enterServiceName: { en: 'Please enter a service name to generate.', ar: 'الرجاء إدخال اسم الخدمة لإنشائها.' },
    generateServiceError: { en: 'Failed to generate service with AI. Please check the format and try again.', ar: 'فشل إنشاء الخدمة بالذكاء الاصطناعي. يرجى التحقق من التنسيق والمحاولة مرة أخرى.' },
    editService: { en: 'Edit Service', ar: 'تعديل الخدمة' },
    serviceDetails: { en: 'New Service Details', ar: 'تفاصيل الخدمة الجديدة' },
    serviceIdPlaceholder: { en: 'Service ID (e.g., service-name)', ar: 'معرف الخدمة (مثال: service-name)' },
    geminiModel: { en: 'Gemini Model', ar: 'نموذج Gemini' },
    titleEnPlaceholder: { en: 'Title (English)', ar: 'العنوان (الإنجليزية)' },
    titleArPlaceholder: { en: 'Title (Arabic)', ar: 'العنوان (العربية)' },
    descriptionEnPlaceholder: { en: 'Description (English)', ar: 'الوصف (الإنجليزية)' },
    descriptionArPlaceholder: { en: 'Description (Arabic)', ar: 'الوصف (العربية)' },
    subCategoryEnPlaceholder: { en: 'Sub-Category (English)', ar: 'فئة فرعية (الإنجليزية)' },
    subCategoryArPlaceholder: { en: 'Sub-Category (Arabic)', ar: 'فئة فرعية (العربية)' },
    icon: { en: 'Icon', ar: 'أيقونة' },
    formInputs: { en: 'Form Inputs', ar: 'حقول الإدخال' },
    inputNamePlaceholder: { en: 'Input Name (snake_case)', ar: 'اسم الحقل (snake_case)' },
    labelEnPlaceholder: { en: 'Label (English)', ar: 'التسمية (الإنجليزية)' },
    labelArPlaceholder: { en: 'Label (Arabic)', ar: 'التسمية (العربية)' },
    options: { en: 'Options', ar: 'الخيارات' },
    addOption: { en: 'Add Option', ar: 'إضافة خيار' },
    addFormInput: { en: 'Add Form Input', ar: 'إضافة حقل إدخال' },
    saveService: { en: 'Save Service', ar: 'حفظ الخدمة' },
    serviceIdRequired: { en: 'Service ID is required.', ar: 'معرف الخدمة مطلوب.' },
    deleteConfirm: { en: 'Are you sure you want to delete this service?', ar: 'هل أنت متأكد من رغبتك في حذف هذه الخدمة؟' },
    serviceDeletedSuccess: { en: 'Service(s) deleted successfully.', ar: 'تم حذف الخدمة (الخدمات) بنجاح.' },
    serviceDeletedError: { en: 'Failed to delete service(s).', ar: 'فشل حذف الخدمة (الخدمات).' },
    existingServices: { en: 'Existing Services', ar: 'الخدمات الحالية' },
    deleteSelected: { en: 'Delete Selected', ar: 'حذف المحدد' },
    serviceName: { en: 'Service Name', ar: 'اسم الخدمة' },
    subCategory: { en: 'Sub-Category', ar: 'الفئة الفرعية' },
    usage: { en: 'Usage', ar: 'الاستخدام' },
    run: { en: 'Run', ar: 'تشغيل' },
    noServicesFound: { en: 'No services found for this category.', ar: 'لم يتم العثور على خدمات في هذه الفئة.' },
    fetchServicesError: { en: 'Failed to load services.', ar: 'فشل تحميل الخدمات.' },
    deleteSelectedConfirm: { en: 'Are you sure you want to delete the {count} selected services?', ar: 'هل أنت متأكد من رغبتك في حذف {count} من الخدمات المحددة؟' },

    // Admin - Subscription Management
    plan: { en: 'Plan', ar: 'الخطة' },
    endsOn: { en: 'Ends On', ar: 'ينتهي في' },
    type: { en: 'Type', ar: 'النوع' },
    noActiveSubscription: { en: 'No active subscriptions found.', ar: 'لم يتم العثور على اشتراكات نشطة.' },
    customPlan: { en: 'Custom / Manual', ar: 'مخصص / يدوي' },
    manageInStripe: { en: 'Manage in Stripe', ar: 'إدارة في Stripe' },
    revoke: { en: 'Revoke', ar: 'إلغاء' },
    revokeConfirm: { en: 'Are you sure you want to revoke this manual subscription?', ar: 'هل أنت متأكد من رغبتك في إلغاء هذا الاشتراك اليدوي؟' },
    revokeSuccess: { en: 'Subscription revoked successfully.', ar: 'تم إلغاء الاشتراك بنجاح.' },
    revokeError: { en: 'Failed to revoke subscription.', ar: 'فشل إلغاء الاشتراك.' },
    fetchSubsError: { en: 'Failed to load subscriptions.', ar: 'فشل تحميل الاشتراكات.' },

    // Admin - Plan Management
    addNewPlan: { en: 'Add New Plan', ar: 'إضافة خطة جديدة' },
    editPlan: { en: 'Edit Plan', ar: 'تعديل الخطة' },
    planId: { en: 'Plan ID (e.g., monthly-basic)', ar: 'معرف الخطة (مثال: monthly-basic)' },
    priceId: { en: 'Stripe Price ID (price_...)', ar: 'معرف السعر في Stripe (price_...)' },
    planTitleEn: { en: 'Plan Title (English)', ar: 'عنوان الخطة (الإنجليزية)' },
    planTitleAr: { en: 'Plan Title (Arabic)', ar: 'عنوان الخطة (العربية)' },
    planPriceEn: { en: 'Price Display (English, e.g., $19/mo)', ar: 'عرض السعر (الإنجليزية، مثال: $19/شهر)' },
    planPriceAr: { en: 'Price Display (Arabic, e.g., ٧٥ ر.س/شهر)', ar: 'عرض السعر (العربية، مثال: ٧٥ ر.س/شهر)' },
    planTokens: { en: 'Tokens included', ar: 'الرموز المضمنة' },
    isPopular: { en: 'Mark as Most Popular', ar: 'تحديد كالأكثر شيوعاً' },
    planFeatures: { en: 'Plan Features', ar: 'مميزات الخطة' },
    featureEn: { en: 'Feature (English)', ar: 'الميزة (الإنجليزية)' },
    featureAr: { en: 'Feature (Arabic)', ar: 'الميزة (العربية)' },
    addFeature: { en: 'Add Feature', ar: 'إضافة ميزة' },
    savePlan: { en: 'Save Plan', ar: 'حفظ الخطة' },
    deactivate: { en: 'Deactivate', ar: 'إلغاء التنشيط' },
    activate: { en: 'Activate', ar: 'تنشيط' },
    fetchPlansError: { en: 'Failed to load plans.', ar: 'فشل تحميل الخطط.' },
    planSavedSuccess: { en: 'Plan saved successfully.', ar: 'تم حفظ الخطة بنجاح.' },
    planSavedError: { en: 'Failed to save plan.', ar: 'فشل حفظ الخطة.' },
    planStatusUpdated: { en: 'Plan status updated.', ar: 'تم تحديث حالة الخطة.' },
    planStatusUpdateError: { en: 'Failed to update plan status.', ar: 'فشل تحديث حالة الخطة.' },

    // Admin - Site Settings
    siteNameEn: { en: 'Site Name (English)', ar: 'اسم الموقع (الإنجليزية)' },
    siteNameAr: { en: 'Site Name (Arabic)', ar: 'اسم الموقع (العربية)' },
    siteSubtitleEn: { en: 'Site Subtitle (English)', ar: 'العنوان الفرعي للموقع (الإنجليزية)' },
    siteSubtitleAr: { en: 'Site Subtitle (Arabic)', ar: 'العنوان الفرعي للموقع (العربية)' },
    metaDescriptionEn: { en: 'Meta Description (English)', ar: 'الوصف التعريفي (الإنجليزية)' },
    metaDescriptionAr: { en: 'Meta Description (Arabic)', ar: 'الوصف التعريفي (العربية)' },
    seoKeywordsEn: { en: 'SEO Keywords (English, comma-separated)', ar: 'كلمات SEO (الإنجليزية، مفصولة بفواصل)' },
    seoKeywordsAr: { en: 'SEO Keywords (Arabic, comma-separated)', ar: 'كلمات SEO (العربية، مفصولة بفواصل)' },
    logo: { en: 'Logo', ar: 'الشعار' },
    favicon: { en: 'Favicon', ar: 'أيقونة الموقع' },
    enableMaintenance: { en: 'Enable Maintenance Mode', ar: 'تفعيل وضع الصيانة' },
    saveSettings: { en: 'Save Settings', ar: 'حفظ الإعدادات' },
    settingsSavedSuccess: { en: 'Settings saved successfully.', ar: 'تم حفظ الإعدادات بنجاح.' },
    settingsSavedError: { en: 'Failed to save settings.', ar: 'فشل حفظ الإعدادات.' },
    customPageActive: { en: 'Custom Page Active', ar: 'صفحة مخصصة نشطة' },
    defaultPageActive: { en: 'Default Page Active', ar: 'صفحة افتراضية نشطة' },
    resetToDefault: { en: 'Reset to Default', ar: 'إعادة للوضع الافتراضي' },
    resetLandingConfirm: { en: 'Are you sure you want to reset the landing page to its default content?', ar: 'هل أنت متأكد من رغبتك في إعادة تعيين الصفحة الرئيسية إلى محتواها الافتراضي؟' },
    landingResetSuccess: { en: 'Landing page has been reset to default.', ar: 'تمت إعادة الصفحة الرئيسية إلى الوضع الافتراضي.' },
    generateWithAIConfig: { en: 'Generate Landing Page with AI', ar: 'إنشاء صفحة رئيسية بالذكاء الاصطناعي' },
    enterTopic: { en: 'Enter a topic, e.g., "AI for corporate law"', ar: 'أدخل موضوعًا، مثال: "الذكاء الاصطناعي لقانون الشركات"' },
    landingGeneratedSuccess: { en: 'New landing page configuration generated and saved!', ar: 'تم إنشاء وحفظ إعدادات الصفحة الرئيسية الجديدة!' },
    landingGenerateFailed: { en: 'Failed to generate landing page content.', ar: 'فشل إنشاء محتوى الصفحة الرئيسية.' },

    // Admin - Marketing
    adPixels: { en: 'Ad Pixels', ar: 'بكسلات الإعلانات' },
    adPixelsDesc: { en: 'Add tracking IDs for your advertising campaigns.', ar: 'أضف معرفات التتبع لحملاتك الإعلانية.' },
    googleTagId: { en: 'Google Tag ID (G-...)', ar: 'معرف علامة جوجل (G-...)' },
    facebookPixelId: { en: 'Facebook Pixel ID', ar: 'معرف بكسل فيسبوك' },
    snapchatPixelId: { en: 'Snapchat Pixel ID', ar: 'معرف بكسل سناب شات' },
    tiktokPixelId: { en: 'TikTok Pixel ID', ar: 'معرف بكسل تيك توك' },

    // Admin - Support
    openTicket: { en: 'Open New Ticket', ar: 'فتح تذكرة جديدة' },
    ticketSubject: { en: 'Subject', ar: 'الموضوع' },
    ticketType: { en: 'Ticket Type', ar: 'نوع التذكرة' },
    message: { en: 'Message', ar: 'الرسالة' },
    submitTicket: { en: 'Submit Ticket', ar: 'إرسال التذكرة' },
    typeReply: { en: 'Type your reply...', ar: 'اكتب ردك...' },
    selectTicket: { en: 'Select a ticket to view the conversation.', ar: 'اختر تذكرة لعرض المحادثة.' },
    open: { en: 'Open', ar: 'مفتوحة' },
    closed: { en: 'Closed', ar: 'مغلقة' },
    answered: { en: 'Answered', ar: 'تم الرد' },

    // Admin - Notifications
    createNotification: { en: 'Create Notification', ar: 'إنشاء إشعار' },
    titleEn: { en: 'Title (English)', ar: 'العنوان (الإنجليزية)' },
    titleAr: { en: 'Title (Arabic)', ar: 'العنوان (العربية)' },
    messageEn: { en: 'Message (English)', ar: 'الرسالة (الإنجليزية)' },
    messageAr: { en: 'Message (Arabic)', ar: 'الرسالة (العربية)' },
    notificationType: { en: 'Notification Type', ar: 'نوع الإشعار' },
    info: { en: 'Info', ar: 'معلومات' },
    success: { en: 'Success', ar: 'نجاح' },
    warning: { en: 'Warning', ar: 'تحذير' },
    alert: { en: 'Alert', ar: 'تنبيه' },
    notificationCreated: { en: 'Notification created successfully.', ar: 'تم إنشاء الإشعار بنجاح.' },
    notificationFailed: { en: 'Failed to create notification.', ar: 'فشل إنشاء الإشعار.' },
    noNotificationsFound: { en: 'No notifications have been created yet.', ar: 'لم يتم إنشاء أي إشعارات بعد.' },
    areYouSure: { en: 'Are you sure?', ar: 'هل أنت متأكد؟' },

    // Subscription Page
    chooseYourPlan: { en: 'Choose Your Plan', ar: 'اختر خطتك' },
    planDescription: { en: 'Select the plan that best suits your needs to get started.', ar: 'اختر الخطة التي تناسب احتياجاتك للبدء.' },
    redirectingToPayment: { en: 'Redirecting to payment...', ar: 'جاري التوجيه للدفع...' },
    paymentError: { en: 'Could not process payment. Please try again.', ar: 'لم نتمكن من معالجة الدفع. يرجى المحاولة مرة أخرى.' },
    stripeKeysNotConfigured: { en: 'Stripe keys are not configured correctly.', ar: 'مفاتيح Stripe غير مهيأة بشكل صحيح.' },

    // Profile Page
    overview: { en: 'Manage your profile, subscription, and security settings.', ar: 'إدارة ملفك الشخصي واشتراكك وإعدادات الأمان.' },
    profileUpdatedSuccess: { en: 'Profile updated successfully.', ar: 'تم تحديث الملف الشخصي بنجاح.' },
    profileUpdatedError: { en: 'Failed to update profile.', ar: 'فشل تحديث الملف الشخصي.' },
    emailUpdateSuccess: { en: 'A verification link has been sent to your new email address.', ar: 'تم إرسال رابط تحقق إلى عنوان بريدك الإلكتروني الجديد.' },
    emailUpdateError: { en: 'Failed to update email.', ar: 'فشل تحديث البريد الإلكتروني.' },
    passwordUpdateSuccess: { en: 'Password updated successfully.', ar: 'تم تحديث كلمة المرور بنجاح.' },
    passwordUpdateError: { en: 'Failed to update password.', ar: 'فشل تحديث كلمة المرور.' },
    portalError: { en: 'Could not open the customer portal.', ar: 'تعذر فتح بوابة العملاء.' },
    subscription: { en: 'Subscription', ar: 'الاشتراك' },
    noSubscription: { en: 'No Active Plan', ar: 'لا توجد خطة نشطة' },
    canceledOn: { en: 'Canceled, ends on', ar: 'ملغى، ينتهي في' },
    renewsOn: { en: 'Renews on', ar: 'يتجدد في' },
    manageSubscription: { en: 'Manage Subscription', ar: 'إدارة الاشتراك' },
    upgradeNow: { en: 'Upgrade Now', ar: 'الترقية الآن' },
    editProfile: { en: 'Personal Information', ar: 'المعلومات الشخصية' },
    fullName: { en: 'Full Name', ar: 'الاسم الكامل' },
    location: { en: 'Location (Country/City)', ar: 'الموقع (الدولة/المدينة)' },
    locationPlaceholder: { en: 'e.g., Riyadh, Saudi Arabia', ar: 'مثال: الرياض، المملكة العربية السعودية' },
    saveChanges: { en: 'Save Changes', ar: 'حفظ التغييرات' },
    security: { en: 'Security', ar: 'الأمان' },
    changeEmail: { en: 'Change Email Address', ar: 'تغيير البريد الإلكتروني' },
    newEmail: { en: 'New Email Address', ar: 'البريد الإلكتروني الجديد' },
    updateEmail: { en: 'Update Email', ar: 'تحديث البريد' },
    changePassword: { en: 'Change Password', ar: 'تغيير كلمة المرور' },
    newPassword: { en: 'New Password', ar: 'كلمة المرور الجديدة' },
    updatePassword: { en: 'Update Password', ar: 'تحديث كلمة المرور' },
    reAuthRequired: { en: 'Authentication Required', ar: 'المصادقة مطلوبة' },
    reAuthMessage: { en: 'For your security, please enter your current password to continue.', ar: 'لأمانك، يرجى إدخال كلمة المرور الحالية للمتابعة.' },
    currentPassword: { en: 'Current Password', ar: 'كلمة المرور الحالية' },
    authenticate: { en: 'Authenticate', ar: 'مصادقة' },
    authenticationError: { en: 'Authentication failed. Please check your password.', ar: 'فشلت المصادقة. يرجى التحقق من كلمة المرور.' },

    // Chat Widget
    aiAssistant: { en: 'AI Assistant', ar: 'المساعد الذكي' },
    typeMessage: { en: 'Type a message...', ar: 'اكتب رسالة...' },
    chatWithAI: { en: 'Chat with AI', ar: 'الدردشة مع المساعد' },

    // Support Modal/Page
    technicalSupportType: { en: 'Technical Support', ar: 'دعم فني' },
    additionalService: { en: 'Request Additional Service', ar: 'طلب خدمة إضافية' },
    specialSubscription: { en: 'Inquire about Special Subscription', ar: 'استفسار عن اشتراك خاص' },
    noTickets: { en: 'No support tickets found.', ar: 'لم يتم العثور على تذاكر دعم.' },
    
    // Footer
    disclaimerTitle: { en: 'Disclaimer', ar: 'إخلاء مسؤولية' },
    disclaimerText: { en: 'The Smart Assistant is a tool powered by artificial intelligence to assist legal professionals. It does not provide legal advice, and its outputs must be reviewed by a qualified lawyer before use. The user is solely responsible for the final legal work product.', ar: 'المساعد الذكي هو أداة مدعومة بالذكاء الاصطناعي لمساعدة المتخصصين في المجال القانوني. لا يقدم استشارات قانونية، ويجب مراجعة مخرجاته من قبل محامٍ مؤهل قبل استخدامها. المستخدم هو المسؤول الوحيد عن المنتج القانوني النهائي.' },
    copyrightText: { en: '© 2024 The Smart Assistant. All rights reserved.', ar: '© 2024 المساعد الذكي. جميع الحقوق محفوظة.' },
    technicalSupport: { en: 'Technical Support', ar: 'الدعم الفني' },

    // App-level
    maintenanceMode: { en: 'Under Maintenance', ar: 'تحت الصيانة' },
    maintenanceMessage: { en: 'We are currently performing scheduled maintenance. Please check back shortly.', ar: 'نقوم حاليًا بإجراء صيانة مجدولة. يرجى العودة قريبًا.' },
};