
// FIX: Import React to make React.ComponentType available.
import React from 'react';
import { Translations, Plan } from './types';
import { FileText, Gavel, Briefcase, Shield, Scale, BookOpen, Building2, Home, Copyright, Handshake, Fingerprint, Banknote, Landmark, Users, Ship, Plane, PersonStanding, Percent, Leaf, Swords, Library, UserCheck, ShieldCheck, Gem, Factory, DollarSign, Recycle, HeartHandshake, Plus, Trash2, Edit, Loader2, Play, Workflow, Archive, Server, ClipboardCheck, HeartCrack, UserX, KeyRound, ScanEye, FlaskConical, Wand2, Search, Film, MapPin, Image, Ratio, ScanLine, AudioLines, Volume2, BrainCircuit, Video, ArrowLeft, ArrowRight, File, User, CreditCard, Star, CheckCircle2, Cog, LayoutDashboard, BarChart, LifeBuoy, MessageSquare, Send, Inbox, Tag, Sparkles } from 'lucide-react';

export const ADMIN_EMAIL = 'binawad1@gmail.com';

// ⚠️ هام جداً: هذا الملف هو كود الواجهة الأمامية (Frontend).
// يجب استخدام "المفتاح القابل للنشر" (Publishable Key) الذي يبدأ بـ 'pk_live_...'.
// ❌ لا تستخدم مفتاح 'rk_live_...' (Restricted Key) أو 'sk_live_...' (Secret Key) هنا أبداً.
// المفاتيح التي تبدأ بـ rk_ أو sk_ ستتسبب في تعليق صفحة الدفع ولن تعمل.

// IMPORTANT: Use your Stripe LIVE Publishable Key here.
// It MUST start with 'pk_live_'. Do NOT use 'rk_live_' or 'sk_live_'.
export const STRIPE_PUBLISHABLE_KEY = 'pk_live_51MHLcOIYFzPtizLNW6GO3QlnhsgSqNz1oTaBnKaFrg0xcoNej1mGufkKgKIP8Vb1CIrXBbHD5tfVVTQo62mgAEmK00dmJQrd28';

export const iconMap: { [key: string]: React.ComponentType<{ className?: string }> } = {
  FileText, Gavel, Briefcase, Shield, Scale, BookOpen, Building2, Home, Copyright, Handshake, Fingerprint, Banknote, Landmark, Users, Ship, Plane, PersonStanding, Percent, Leaf, Swords, Library, UserCheck, ShieldCheck, Gem, Factory, DollarSign, Recycle, HeartHandshake, Plus, Trash2, Edit, Loader2, Play, Workflow, Archive, Server, ClipboardCheck, HeartCrack, UserX, KeyRound, ScanEye, FlaskConical, Wand2, Search, Film, MapPin, Image, Ratio, ScanLine, AudioLines, Volume2, BrainCircuit, Video, ArrowLeft, ArrowRight, File, User, CreditCard, Star, CheckCircle2, Cog, LayoutDashboard, BarChart, LifeBuoy, MessageSquare, Send, Inbox, Tag, Sparkles,
  // FIX: Alias non-existent 'AspectRatio' icon to 'Ratio' for backward compatibility.
  AspectRatio: Ratio,
  // FIX: Alias non-existent 'Body' icon to 'PersonStanding' to prevent app crash from bad seed data.
  Body: PersonStanding,
};

export const iconNames = Object.keys(iconMap);

export const translations: Translations = {
  // General
  appName: { en: 'The Smart Assistant', ar: 'المساعد الذكي' },
  appSubtitle: { en: 'For Law & Legal Consultations', ar: 'للمحاماة والاستشارات القانونية' },
  startWithUs: { en: 'Start With Us', ar: 'ابدأ معنا' },
  login: { en: 'Login', ar: 'تسجيل الدخول' },
  signup: { en: 'Sign Up', ar: 'تسجيل جديد' },
  logout: { en: 'Logout', ar: 'تسجيل الخروج' },
  email: { en: 'Email', ar: 'البريد الإلكتروني' },
  password: { en: 'Password', ar: 'كلمة المرور' },
  confirmPassword: { en: 'Confirm Password', ar: 'تأكيد كلمة المرور' },
  dontHaveAccount: { en: "Don't have an account?", ar: 'ليس لديك حساب؟' },
  alreadyHaveAccount: { en: 'Already have an account?', ar: 'لديك حساب بالفعل؟' },
  loading: { en: 'Loading...', ar: 'جاري التحميل...' },
  close: { en: 'Close', ar: 'إغلاق' },
  home: { en: 'Home', ar: 'الرئيسية' },
  services: { en: 'Services', ar: 'الخدمات' },
  
  // Location & Context
  location: { en: 'Jurisdiction / Country', ar: 'النطاق الجغرافي / الدولة' },
  detectingLocation: { en: 'Detecting location...', ar: 'جاري تحديد الموقع...' },
  locationPlaceholder: { en: 'e.g., Saudi Arabia, UAE', ar: 'مثال: السعودية، الإمارات' },
  locationAwarenessMessage: { 
      en: 'From the moment you enter... the system automatically identifies your jurisdiction and formulates legal information and services compliant with local regulations.', 
      ar: 'من لحظة دخولك... النظام يحدد بلدك تلقائيًا ويصيغ لك معلومات وخدمات قانونية متوافقة مع الأنظمة المحلية.' 
  },
  yourLocation: { en: 'Your Location', ar: 'نطاقك الجغرافي' },

  // Landing Page
  landingTitle: { en: 'AI-Powered Legal Services', ar: 'خدمات قانونية مدعومة بالذكاء الاصطناعي' },
  landingDescription: { en: 'We specialize in providing advanced AI solutions for law firms and legal consultants to enhance efficiency and accuracy.', ar: 'نحن متخصصون في تقديم حلول الذكاء الاصطناعي المتقدمة لمكاتب المحاماة والمستشارين القانونيين لتعزيز الكفاءة والدقة.' },
  heroTitleMain: { en: 'Your Legal Assistant', ar: 'مساعدك القانوني' },
  heroTitleHighlight: { en: 'Powered by AI', ar: 'المدعوم بالذكاء الاصطناعي' },
  heroSubtitle: { en: 'Streamline your legal work, from case analysis to document drafting, with the power of artificial intelligence. Get started with a free trial.', ar: 'بسّط أعمالك القانونية، من تحليل القضايا إلى صياغة المستندات، بقوة الذكاء الاصطناعي. ابدأ الآن بتجربة مجانية.' },
  startFreeTrial: { en: 'Start Your Free Trial', ar: 'ابدأ تجربتك المجانية' },
  goToDashboard: { en: 'Go to Dashboard', ar: 'الذهاب إلى لوحة التحكم' },
  featuresTitle: { en: 'Unlock Powerful Features', ar: 'اكتشف ميزات قوية' },
  feature1Title: { en: 'Instant Document Analysis', ar: 'تحليل فوري للمستندات' },
  feature1Desc: { en: 'Upload your legal documents and get summaries, risk assessments, and key clause identification in seconds.', ar: 'ارفع مستنداتك القانونية واحصل على ملخصات وتقييمات للمخاطر وتحديد للبلاغات الرئيسية في ثوانٍ.' },
  feature2Title: { en: 'Smart Legal Research', ar: 'بحث قانوني ذكي' },
  feature2Desc: { en: 'Ask complex legal questions in natural language and receive precise, AI-driven answers and precedents.', ar: 'اطرح أسئلة قانونية معقدة بلغة طبيعية واحصل على إجابات وسوابق قضائية دقيقة مدعومة بالذكاء الاصطناعي.' },
  feature3Title: { en: 'Automated Drafting', ar: 'صياغة آلية' },
  feature3Desc: { en: 'Generate first drafts of memos, pleadings, and contracts, saving you valuable time and effort.', ar: 'أنشئ مسودات أولية للمذكرات والمرافعات والعقود، مما يوفر لك وقتاً وجهداً ثمينين.' },
  feature4Title: { en: 'Legal Risk Assessment', ar: 'تقييم المخاطر القانونية' },
  feature4Desc: { en: 'Identify potential liabilities and compliance issues in contracts before they arise.', ar: 'تحديد الالتزامات المحتملة ومشاكل الامتثال في العقود قبل نشوئها.' },
  feature5Title: { en: 'Strategic Case Planning', ar: 'تخطيط استراتيجية القضايا' },
  feature5Desc: { en: 'Develop data-driven legal strategies based on precedents and probability analysis.', ar: 'تطوير استراتيجيات قانونية مبنية على البيانات بناءً على السوابق وتحليل الاحتمالات.' },
  feature6Title: { en: 'Regulatory Compliance', ar: 'الامتثال التنظيمي' },
  feature6Desc: { en: 'Stay compliant with the latest regulations and avoid costly penalties.', ar: 'حافظ على الامتثال لأحدث اللوائح وتجنب العقوبات المكلفة.' },
  feature7Title: { en: 'Client Communication', ar: 'التواصل مع العملاء' },
  feature7Desc: { en: 'Generate professional responses and updates for your clients instantly.', ar: 'إنشاء ردود وتحديثات احترافية لعملائك فوراً.' },
  feature8Title: { en: 'Legal Translation', ar: 'الترجمة القانونية' },
  feature8Desc: { en: 'Accurate translation of legal terminology between Arabic and English.', ar: 'ترجمة دقيقة للمصطلحات القانونية بين العربية والإنجليزية.' },
  feature9Title: { en: 'Smart Archiving', ar: 'الأرشفة الذكية' },
  feature9Desc: { en: 'Organize and retrieve legal knowledge and case files efficiently.', ar: 'تنظيم واسترجاع المعرفة القانونية وملفات القضايا بكفاءة.' },
  pricingTitle: { en: 'Choose Your Plan', ar: 'اختر باقتك' },
  pricingSubtitle: { en: 'Simple, transparent pricing to fit your needs. Start for free and upgrade as you grow.', ar: 'تسعير بسيط وشفاف يناسب احتياجاتك. ابدأ مجاناً وقم بالترقية مع نمو أعمالك.' },
  finalCtaTitle: { en: 'Ready to Transform Your Legal Practice?', ar: 'هل أنت مستعد لتغيير ممارستك القانونية؟' },
  finalCtaSubtitle: { en: 'Join hundreds of legal professionals who are working smarter, not harder.', ar: 'انضم إلى مئات المحترفين القانونيين الذين يعملون بذكاء أكبر، وليس بجهد أكبر.' },
  signUpForFree: { en: 'Sign Up For Free', ar: 'سجل مجاناً' },

  // Dashboard
  welcomeBack: { en: 'Welcome back', ar: 'مرحباً بعودتك' },
  searchServices: { en: 'Search for services...', ar: 'ابحث عن الخدمات...' },
  litigationAndPleadings: { en: 'Litigation and Court Pleadings', ar: 'المحاماة والمرافعات القضائية' },
  specializedConsultations: { en: 'Specialized Legal Consultations', ar: 'الاستشارات القانونية المتخصصة' },
  investigationsAndCriminal: { en: 'Investigations and Criminal Services', ar: 'التحقيقات والخدمات الجنائية' },
  corporateAndCompliance: { en: 'Corporate Services and Legal Compliance', ar: 'خدمات الشركات والامتثال القانوني' },
  creativeServices: { en: 'Creative & Special Services', ar: 'الخدمات الإبداعية والخاصة' },
  creativeServicesDesc: { en: 'Unlock the power of generative AI for drafting, content creation, and specialized tasks.', ar: 'اكتشف قوة الذكاء الاصطناعي التوليدي للصياغة وإنشاء المحتوى والمهام الخاصة.' },
  executeTask: { en: 'Execute Task', ar: 'تنفيذ المهمة' },
  exportToPdf: { en: 'Export to PDF', ar: 'تصدير إلى PDF' },
  results: { en: 'Results', ar: 'النتائج' },
  generatingResponse: { en: 'Generating response, please wait...', ar: 'جاري إنشاء الرد، يرجى الانتظار...' },
  modelIsBusyRetrying: { en: 'The model is busy. Retrying... (Attempt ${attempt} of ${maxRetries})', ar: 'النموذج مشغول حالياً. جاري إعادة المحاولة... (محاولة ${attempt} من ${maxRetries})' },
  noServicesFound: { en: 'No services found matching your criteria.', ar: 'لم يتم العثور على خدمات تطابق معاييرك.' },
  noServicesInCategory: { en: 'There are no services in this category yet.', ar: 'لا توجد خدمات في هذه الفئة بعد.' },
  failedToLoadServices: { en: "Failed to load services. Please try again later.", ar: "فشل تحميل الخدمات. يرجى المحاولة مرة أخرى لاحقًا."},
  resultPlaceholder: { en: "The result will appear here.", ar: "ستظهر النتيجة هنا." },
  uploadFile: { en: "Upload a file", ar: "رفع ملف" },
  noFileSelected: { en: "No file selected", ar: "لم يتم اختيار ملف" },
  legalAssistant: { en: 'The Legal Assistant', ar: 'المساعد القانوني' },
  howCanIHelp: { en: 'How can I help you today?', ar: 'كيف يمكنني مساعدتك اليوم؟' },
  poweredByAI: { en: 'Powered by AI', ar: 'مدعوم بالذكاء الاصطناعي' },
  typeYourRequest: { en: 'Type your request here...', ar: 'اكتب طلبك هنا...' },
  execute: { en: 'Execute', ar: 'تنفيذ' },
  smartLegalAssistant: { en: 'Your Smart Legal Assistant', ar: 'مساعدك القانوني الذكي' },
  selectServiceToStart: { en: 'Select a service or type your request to begin.', ar: 'اختر خدمة أو اكتب طلبك لتبدأ.' },
  copy: { en: 'Copy', ar: 'نسخ' },
  copied: { en: 'Copied!', ar: 'تم النسخ!' },
  print: { en: 'Print', ar: 'طباعة' },
  listen: { en: 'Listen', ar: 'استماع' },
  stop: { en: 'Stop', ar: 'إيقاف' },
  basicServices: { en: 'Basic Services', ar: 'الخدمات الأساسية' },
  advancedServices: { en: 'Creative & General Services', ar: 'الخدمات الإبداعية والعامة' },
  tokenBalance: { en: 'Token Balance', ar: 'رصيد التوكن' },
  tokens: { en: 'Tokens', ar: 'توكن' },
  outOfTokens: { en: 'Your token balance is zero.', ar: 'رصيدك من التوكنات هو صفر.' },
  outOfTokensAdmin: { en: 'Please contact an administrator to recharge your account.', ar: 'يرجى التواصل مع المسؤول لإعادة شحن حسابك.'},
  outOfTokensUser: { en: 'Please upgrade your plan to continue using our services.', ar: 'يرجى ترقية خطتك لمواصلة استخدام خدماتنا.'},
  upgradeNow: { en: 'Upgrade Now', ar: 'الترقية الآن' },
  addTokens: { en: 'Add Tokens', ar: 'إضافة رصيد' },
  enterTokenAmount: { en: 'Enter the number of tokens to add:', ar: 'أدخل عدد التوكنات المراد إضافتها:' },
  add: { en: 'Add', ar: 'إضافة' },
  tokensAddedSuccess: { en: 'Tokens added successfully!', ar: 'تمت إضافة الرصيد بنجاح!' },
  outputLanguage: { en: 'Output Language', ar: 'لغة المخرجات' },
  arabic: { en: 'Arabic', ar: 'العربية' },
  english: { en: 'English', ar: 'الإنجليزية' },

  // Admin
  adminPanel: { en: 'Admin Panel', ar: 'لوحة الإدارة' },
  userManagement: { en: 'User Management', ar: 'إدارة المستخدمين' },
  subscriptionManagement: { en: 'Subscription Management', ar: 'إدارة الاشتراكات' },
  planManagement: { en: 'Plan Management', ar: 'إدارة الباقات' },
  siteSettings: { en: 'Site Settings', ar: 'إعدادات الموقع' },
  marketing: { en: 'Marketing & Tracking', ar: 'التسويق والربط' },
  grantSubscription: { en: 'Grant Subscription', ar: 'منح اشتراك' },
  grant: { en: 'Grant', ar: 'منح' },
  selectUser: { en: 'Select User', ar: 'اختر مستخدم' },
  selectPlan: { en: 'Select Plan', ar: 'اختر باقة' },
  customPlan: { en: 'Custom', ar: 'مخصص' },
  tokenAmount: { en: 'Token Amount', ar: 'كمية التوكن' },
  durationDays: { en: 'Duration (in days)', ar: 'المدة (بالأيام)' },
  noSubscription: { en: 'No Subscription', ar: 'لا يوجد اشتراك' },
  manageInStripe: { en: 'Manage in Stripe', ar: 'إدارة في Stripe' },
  revoke: { en: 'Revoke', ar: 'إلغاء' },
  revokeConfirm: { en: 'Are you sure you want to revoke this manual subscription?', ar: 'هل أنت متأكد من رغبتك في إلغاء هذا الاشتراك اليدوي؟' },
  grantSuccess: { en: 'Subscription granted successfully!', ar: 'تم منح الاشتراك بنجاح!' },
  grantError: { en: 'Failed to grant subscription.', ar: 'فشل منح الاشتراك.' },
  revokeSuccess: { en: 'Subscription revoked successfully.', ar: 'تم إلغاء الاشتراك بنجاح.' },
  revokeError: { en: 'Failed to revoke subscription.', ar: 'فشل إلغاء الاشتراك.' },
  fetchSubsError: { en: 'Failed to fetch user subscriptions.', ar: 'فشل جلب اشتراكات المستخدمين.' },
  noUsersToGrant: { en: 'All users already have an active subscription.', ar: 'جميع المستخدمين لديهم اشتراك نشط بالفعل.' },
  addService: { en: 'Add Service', ar: 'إضافة خدمة' },
  edit: { en: 'Edit', ar: 'تعديل' },
  actions: { en: 'Actions', ar: 'إجراءات' },
  role: { en: 'Role', ar: 'الدور' },
  dateJoined: { en: 'Date Joined', ar: 'تاريخ الانضمام' },
  manageServices: { en: 'Manage Services', ar: 'إدارة الخدمات' },
  addNewService: { en: 'Add New Service', ar: 'إضافة خدمة جديدة' },
  editService: { en: 'Edit Service', ar: 'تعديل الخدمة' },
  serviceIdPlaceholder: { en: 'Service ID (e.g., contract-analysis)', ar: 'معرف الخدمة (مثال: contract-analysis)' },
  titleEnPlaceholder: { en: 'Title (EN)', ar: 'العنوان (EN)' },
  titleArPlaceholder: { en: 'Title (AR)', ar: 'العنوان (AR)' },
  descriptionEnPlaceholder: { en: 'Description (EN)', ar: 'الوصف (EN)' },
  descriptionArPlaceholder: { en: 'Description (AR)', ar: 'الوصف (AR)' },
  subCategoryEnPlaceholder: { en: 'Sub-category (EN)', ar: 'فئة فرعية (EN)' },
  subCategoryArPlaceholder: { en: 'Sub-category (AR)', ar: 'فئة فرعية (AR)' },
  geminiModel: { en: 'Gemini Model', ar: 'نموذج Gemini' },
  category: { en: 'Category', ar: 'الفئة' },
  icon: { en: 'Icon', ar: 'أيقونة' },
  formInputs: { en: 'Form Inputs', ar: 'حقول النموذج' },
  input: { en: 'Input', ar: 'إدخال' },
  inputNamePlaceholder: { en: 'Name (e.g., contract_file)', ar: 'الاسم (مثال: contract_file)' },
  labelEnPlaceholder: { en: 'Label (EN)', ar: 'التسمية (EN)' },
  labelArPlaceholder: { en: 'Label (AR)', ar: 'التسمية (AR)' },
  inputType: { en: 'Type', ar: 'النوع' },
  addFormInput: { en: 'Add Form Input', ar: 'إضافة حقل إدخال' },
  options: { en: 'Options', ar: 'خيارات' },
  optionValuePlaceholder: { en: 'Option Value', ar: 'قيمة الخيار' },
  addOption: { en: 'Add Option', ar: 'إضافة خيار' },
  saveService: { en: 'Save Service', ar: 'حفظ الخدمة' },
  existingServices: { en: 'Existing Services', ar: 'الخدمات الحالية' },
  deleteConfirm: { en: 'Are you sure you want to delete this service?', ar: 'هل أنت متأكد أنك تريد حذف هذه الخدمة؟' },
  serviceSavedSuccess: { en: 'Service saved successfully!', ar: 'تم حفظ الخدمة بنجاح!' },
  serviceSavedError: { en: 'Failed to save service.', ar: 'فشل حفظ الخدمة.' },
  serviceDeletedSuccess: { en: 'Service deleted successfully!', ar: 'تم حذف الخدمة بنجاح!' },
  serviceDeletedError: { en: 'Failed to delete service.', ar: 'فشل حذف الخدمة.' },
  serviceIdRequired: { en: 'Service ID is required.', ar: 'معرف الخدمة مطلوب.' },
  fetchUsersError: { en: 'An error occurred while fetching users.', ar: 'حدث خطأ أثناء جلب المستخدمين.' },
  fetchUsersIndexError: { en: "Error: The database query requires an index. Please check the browser console for a link to create it in your Firebase project.", ar: "خطأ: يتطلب استعلام قاعدة البيانات فهرسًا. يرجى مراجعة وحدة تحكم المتصفح للحصول على رابط لإنشائه في مشروع Firebase الخاص بك." },
  noUsersFound: { en: 'No users found.', ar: 'لم يتم العثور على مستخدمين.' },
  fetchServicesError: { en: "Failed to fetch services.", ar: "فشل في جلب الخدمات."},
  passwordsDontMatch: { en: "Passwords do not match.", ar: "كلمات المرور غير متطابقة." },
  status: { en: 'Status', ar: 'الحالة' },
  active: { en: 'Active', ar: 'نشط' },
  disabled: { en: 'Disabled', ar: 'معطل' },
  inactive: { en: 'Inactive', ar: 'غير نشط' },
  enable: { en: 'Enable', ar: 'تفعيل' },
  disable: { en: 'Disable', ar: 'تعطيل' },
  delete: { en: 'Delete', ar: 'حذف' },
  enableUserConfirm: { en: 'Are you sure you want to enable this user?', ar: 'هل أنت متأكد أنك تريد تفعيل هذا المستخدم؟' },
  disableUserConfirm: { en: 'Are you sure you want to disable this user?', ar: 'هل أنت متأكد أنك تريد تعطيل هذا المستخدم؟' },
  deleteUserConfirm: { en: 'Are you sure you want to delete this user? This will delete their data but not their authentication account. This action cannot be undone.', ar: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟ سيؤدي هذا إلى حذف بياناته ولكن ليس حساب المصادقة الخاص به. لا يمكن التراجع عن هذا الإجراء.' },
  userUpdatedSuccess: { en: 'User status updated successfully.', ar: 'تم تحديث حالة المستخدم بنجاح.' },
  userUpdatedError: { en: 'Failed to update user status.', ar: 'فشل تحديث حالة المستخدم.' },
  userDeletedError: { en: 'Failed to delete user.', ar: 'فشل حذف المستخدم.' },
  userDeletedSuccess: { en: 'User deleted successfully.', ar: 'تم حذف المستخدم بنجاح.' },
  generateWithAI: { en: 'Generate with AI', ar: 'إنشاء باستخدام الذكاء الاصطناعي' },
  generate: { en: 'Generate', ar: 'إنشاء' },
  generating: { en: 'Generating...', ar: 'جاري الإنشاء...' },
  serviceNamePlaceholder: { en: 'Enter service name (e.g., "Analyze a commercial contract")', ar: 'أدخل اسم الخدمة (مثال: "تحليل عقد تجاري")' },
  aiGeneratorDescription: { en: 'Enter a service name, and the AI will generate a complete configuration. You can review and edit the details before saving.', ar: 'أدخل اسم الخدمة، وسيقوم الذكاء الاصطناعي بإنشاء تكوين كامل. يمكنك مراجعة التفاصيل وتعديلها قبل الحفظ.' },
  serviceDetails: { en: 'Service Details', ar: 'تفاصيل الخدمة' },
  enterServiceName: { en: 'Please enter a service name to generate details.', ar: 'يرجى إدخال اسم الخدمة لإنشاء التفاصيل.' },
  generateServiceError: { en: 'Failed to generate service with AI. Please check the console for details or try again.', ar: 'فشل إنشاء الخدمة باستخدام الذكاء الاصطناعي. يرجى مراجعة وحدة التحكم للحصول على التفاصيل أو المحاولة مرة أخرى.' },
  serviceName: { en: 'Service Name', ar: 'اسم الخدمة' },
  subCategory: { en: 'Sub-category', ar: 'القسم الخاص' },
  usage: { en: 'Usage', ar: 'الاستخدامات' },
  run: { en: 'Run', ar: 'تشغيل' },
  runService: { en: 'Run Service', ar: 'شغّل الخدمة' },
  timesUsed: { en: 'times used', ar: 'مرة استخدام' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  databaseSeeding: { en: 'Database Seeding', ar: 'تعبئة قاعدة البيانات' },
  databaseSeedingDescription: { en: 'Quickly populate the database with predefined service sets.', ar: 'تعبئة قاعدة البيانات بسرعة بمجموعات خدمات محددة مسبقًا.' },
  seedLitigationButton: { en: 'Seed Litigation Services', ar: 'تعبئة خدمات المرافعات' },
  seedConsultationsButton: { en: 'Seed Consultation Services', ar: 'تعبئة خدمات الاستشارات' },
  seedInvestigationsButton: { en: 'Seed Investigation Services', ar: 'تعبئة خدمات التحقيقات' },
  seedCorporateButton: { en: 'Seed Corporate Services', ar: 'تعبئة خدمات الشركات' },
  seedCreativeButton: { en: 'Seed Creative Services', ar: 'تعبئة الخدمات الإبداعية' },
  seedLitigationConfirm: { en: 'Are you sure you want to add all litigation and pleadings services?', ar: 'هل أنت متأكد من رغبتك في إضافة جميع خدمات المحاماة والمرافعات القضائية؟' },
  seedConsultationsConfirm: { en: 'Are you sure you want to add all specialized consultation services?', ar: 'هل أنت متأكد من رغبتك في إضافة جميع خدمات الاستشارات المتخصصة؟' },
  seedInvestigationsConfirm: { en: 'Are you sure you want to add all investigation and criminal services?', ar: 'هل أنت متأكد من رغبتك في إضافة جميع خدمات التحقيقات والخدمات الجنائية؟' },
  seedCorporateConfirm: { en: 'Are you sure you want to add all corporate and compliance services?', ar: 'هل أنت متأكد من رغبتك في إضافة جميع خدمات الشركات والامتثال القانوني؟' },
  seedCreativeConfirm: { en: 'Are you sure you want to add all creative and general services?', ar: 'هل أنت متأكد من رغبتك في إضافة جميع الخدمات الإبداعية والعامة؟' },
  seedingLitigationInProgress: { en: 'Adding litigation services...', ar: 'جاري إضافة خدمات المرافعات...' },
  seedingConsultationsInProgress: { en: 'Adding consultation services...', ar: 'جاري إضافة خدمات الاستشارات...' },
  seedingInvestigationsInProgress: { en: 'Adding investigation services...', ar: 'جاري إضافة خدمات التحقيقات...' },
  seedingCorporateInProgress: { en: 'Adding corporate services...', ar: 'جاري إضافة خدمات الشركات...' },
  seedingCreativeInProgress: { en: 'Adding creative services...', ar: 'جاري إضافة الخدمات الإبداعية...' },
  seedLitigationSuccess: { en: 'Litigation services added successfully!', ar: 'تمت إضافة خدمات المرافعات بنجاح!' },
  seedConsultationsSuccess: { en: 'Specialized consultation services added successfully!', ar: 'تمت إضافة خدمات الاستشارات المتخصصة بنجاح!' },
  seedInvestigationsSuccess: { en: 'Investigation services added successfully!', ar: 'تمت إضافة خدمات التحقيقات بنجاح!' },
  seedCorporateSuccess: { en: 'Corporate services added successfully!', ar: 'تمت إضافة خدمات الشركات بنجاح!' },
  seedCreativeSuccess: { en: 'Creative services added successfully!', ar: 'تمت إضافة الخدمات الإبداعية بنجاح!' },
  allCategories: { en: 'All', ar: 'الكل' },
  deleteSelected: { en: 'Delete Selected', ar: 'حذف المحدد' },
  deleteSelectedConfirm: { en: 'Are you sure you want to delete {count} selected services? This action cannot be undone.', ar: 'هل أنت متأكد أنك تريد حذف {count} من الخدمات المحددة؟ لا يمكن التراجع عن هذا الإجراء.' },
  selectAll: { en: 'Select all', ar: 'تحديد الكل' },
  
  // Plan Management
  addNewPlan: { en: 'Add New Plan', ar: 'إضافة باقة جديدة' },
  editPlan: { en: 'Edit Plan', ar: 'تعديل الباقة' },
  planId: { en: 'Plan ID (e.g., monthly-plan)', ar: 'معرّف الباقة (مثال: monthly-plan)' },
  priceId: { en: 'Stripe Price ID (e.g., price_123abc)', ar: 'معرّف السعر في Stripe (مثال: price_123abc)' },
  planTitleEn: { en: 'Plan Title (EN)', ar: 'عنوان الباقة (EN)' },
  planTitleAr: { en: 'Plan Title (AR)', ar: 'عنوان الباقة (AR)' },
  planPriceEn: { en: 'Display Price (EN) e.g., 250 SAR / month', ar: 'السعر للعرض (EN) مثال: 250 SAR / month' },
  planPriceAr: { en: 'Display Price (AR) e.g., ٢٥٠ ر.س/شهرياً', ar: 'السعر للعرض (AR) مثال: ٢٥٠ ر.س/شهرياً' },
  planTokens: { en: 'Tokens Granted', ar: 'التوكن الممنوح' },
  planFeatures: { en: 'Features', ar: 'الميزات' },
  addFeature: { en: 'Add Feature', ar: 'إضافة ميزة' },
  featureEn: { en: 'Feature (EN)', ar: 'الميزة (EN)' },
  featureAr: { en: 'Feature (AR)', ar: 'الميزة (AR)' },
  isPopular: { en: 'Mark as "Most Popular"', ar: 'تحديد كـ "الأكثر شيوعاً"' },
  planStatus: { en: 'Plan Status', ar: 'حالة الباقة' },
  savePlan: { en: 'Save Plan', ar: 'حفظ الباقة' },
  deletePlanConfirm: { en: 'Are you sure you want to delete this plan?', ar: 'هل أنت متأكد من حذف هذه الباقة؟' },
  planSavedSuccess: { en: 'Plan saved successfully!', ar: 'تم حفظ الباقة بنجاح!' },
  planSavedError: { en: 'Failed to save plan.', ar: 'فشل حفظ الباقة.' },
  planDeletedSuccess: { en: 'Plan deleted successfully!', ar: 'تم حذف الباقة بنجاح!' },
  planDeletedError: { en: 'Failed to delete plan.', ar: 'فشل حذف الباقة.' },
  planStatusUpdated: { en: 'Plan status updated.', ar: 'تم تحديث حالة الباقة.' },
  planStatusUpdateError: { en: 'Failed to update plan status.', ar: 'فشل تحديث حالة الباقة.' },
  noPlansFound: { en: 'No plans found.', ar: 'لم يتم العثور على باقات.' },
  fetchPlansError: { en: 'Failed to fetch plans.', ar: 'فشل جلب الباقات.' },
  activate: { en: 'Activate', ar: 'تفعيل' },
  deactivate: { en: 'Deactivate', ar: 'إلغاء التفعيل' },

  // Profile & Subscriptions
  myProfile: { en: 'My Profile', ar: 'ملفي الشخصي' },
  subscription: { en: 'Subscription', ar: 'الاشتراك' },
  manageSubscription: { en: 'Manage Subscription', ar: 'إدارة الاشتراك' },
  noActiveSubscription: { en: 'You do not have an active subscription.', ar: 'ليس لديك اشتراك نشط.' },
  browsePlans: { en: 'Browse Plans', ar: 'تصفح الخطط' },
  currentPlan: { en: 'Current Plan', ar: 'الخطة الحالية' },
  renewsOn: { en: 'Renews on', ar: 'يتجدد في' },
  endsOn: { en: 'Ends on', ar: 'ينتهي في' },
  canceledOn: { en: 'Expires on', ar: 'ينتهي في' },
  plan: { en: 'Plan', ar: 'الخطة' },
  chooseYourPlan: { en: 'Choose Your Plan', ar: 'اختر خطتك' },
  planDescription: { en: 'Select the plan that best fits your needs and get access to more features and tokens.', ar: 'اختر الخطة التي تناسب احتياجاتك واحصل على المزيد من الميزات والتوكنات.' },
  choosePlan: { en: 'Choose Plan', ar: 'اختر الخطة' },
  mostPopular: { en: 'Most Popular', ar: 'الأكثر شيوعاً' },
  redirectingToPayment: { en: 'Redirecting to payment...', ar: 'جاري التوجيه للدفع...' },
  paymentError: { en: 'An error occurred during the payment process. Please try again.', ar: 'حدث خطأ أثناء عملية الدفع. يرجى المحاولة مرة أخرى.' },
  portalError: { en: 'Could not open the subscription management portal. Please try again later.', ar: 'تعذر فتح بوابة إدارة الاشتراك. يرجى المحاولة مرة أخرى لاحقًا.' },
  stripeKeysNotConfigured: { en: 'Stripe configuration error: Invalid Key. Frontend requires "pk_live_...".', ar: 'خطأ في إعدادات Stripe: مفتاح غير صالح. الواجهة تتطلب مفتاح يبدأ بـ "pk_live_...".' },
  overview: { en: 'Overview', ar: 'نظرة عامة' },
  profile: { en: 'Profile', ar: 'الملف الشخصي' },
  security: { en: 'Security', ar: 'الأمان' },
  editProfile: { en: 'Edit Profile', ar: 'تعديل الملف الشخصي' },
  fullName: { en: 'Full Name', ar: 'الاسم الكامل' },
  saveChanges: { en: 'Save Changes', ar: 'حفظ التغييرات' },
  profileUpdatedSuccess: { en: 'Profile updated successfully!', ar: 'تم تحديث الملف الشخصي بنجاح!' },
  profileUpdatedError: { en: 'Failed to update profile.', ar: 'فشل تحديث الملف الشخصي.' },
  changeEmail: { en: 'Change Email', ar: 'تغيير البريد الإلكتروني' },
  newEmail: { en: 'New Email', ar: 'البريد الإلكتروني الجديد' },
  updateEmail: { en: 'Update Email', ar: 'تحديث البريد الإلكتروني' },
  emailUpdateSuccess: { en: 'Verification email sent! Please check your new email address to complete the change.', ar: 'تم إرسال بريد التحقق! يرجى مراجعة بريدك الإلكتروني الجديد لإتمام التغيير.' },
  emailUpdateError: { en: 'Failed to update email.', ar: 'فشل تحديث البريد الإلكتروني.' },
  changePassword: { en: 'Change Password', ar: 'تغيير كلمة المرور' },
  currentPassword: { en: 'Current Password', ar: 'كلمة المرور الحالية' },
  newPassword: { en: 'New Password', ar: 'كلمة المرور الجديدة' },
  confirmNewPassword: { en: 'Confirm New Password', ar: 'تأكيد كلمة المرور الجديدة' },
  updatePassword: { en: 'Update Password', ar: 'تحديث كلمة المرور' },
  passwordUpdateSuccess: { en: 'Password updated successfully!', ar: 'تم تحديث كلمة المرور بنجاح!' },
  passwordUpdateError: { en: 'Failed to update password.', ar: 'فشل تحديث كلمة المرور.' },
  reAuthRequired: { en: 'Authentication Required', ar: 'مطلوب إعادة المصادقة' },
  reAuthMessage: { en: 'For your security, please enter your current password to continue.', ar: 'لأمانك، يرجى إدخال كلمة المرور الحالية للمتابعة.' },
  authenticate: { en: 'Authenticate', ar: 'مصادقة' },
  authenticationError: { en: 'Authentication failed. Please check your password.', ar: 'فشلت المصادقة. يرجى التحقق من كلمة المرور.' },

  
  // Site Settings
  siteNameEn: { en: 'The Smart Assistant', ar: 'المساعد الذكي' },
  siteNameAr: { en: 'Site Name (Arabic)', ar: 'اسم الموقع (عربي)' },
  logo: { en: 'Logo', ar: 'الشعار' },
  favicon: { en: 'Favicon', ar: 'أيقونة الموقع' },
  metaDescriptionEn: { en: 'Meta Description (English)', ar: 'الوصف التعريفي (إنجليزي)' },
  metaDescriptionAr: { en: 'Meta Description (Arabic)', ar: 'الوصف التعريفي (عربي)' },
  seoKeywordsEn: { en: 'SEO Keywords (English)', ar: 'الكلمات المفتاحية (إنجليزي)' },
  seoKeywordsAr: { en: 'SEO Keywords (Arabic)', ar: 'الكلمات المفتاحية (عربي)' },
  maintenanceMode: { en: 'Maintenance Mode', ar: 'وضع الصيانة' },
  enableMaintenance: { en: 'Enable Maintenance Mode', ar: 'تفعيل وضع الصيانة' },
  maintenanceMessage: { en: 'The site is currently under maintenance. We will be back shortly.', ar: 'الموقع حاليًا تحت الصيانة. سنعود قريبًا.'},
  change: { en: 'Change', ar: 'تغيير' },
  current: { en: 'Current', ar: 'الحالي' },
  saveSettings: { en: 'Save Settings', ar: 'حفظ الإعدادات' },
  settingsSavedSuccess: { en: 'Site settings saved successfully!', ar: 'تم حفظ إعدادات الموقع بنجاح!' },
  settingsSavedError: { en: 'Failed to save site settings.', ar: 'فشل حفظ إعدادات الموقع.' },
  uploadError: { en: 'File upload failed.', ar: 'فشل رفع الملف.' },
  adPixels: { en: 'Advertising Tracking Pixels', ar: 'أكواد التتبع الإعلانية' },
  adPixelsDesc: { en: 'Enter the ID for each platform to enable tracking automatically.', ar: 'أدخل المعرف (ID) لكل منصة لتفعيل التتبع تلقائياً.' },
  googleTagId: { en: 'Google Tag ID (G-xxx / AW-xxx)', ar: 'معرف Google Tag (G-xxx / AW-xxx)' },
  facebookPixelId: { en: 'Facebook Pixel ID', ar: 'معرف Facebook Pixel' },
  snapchatPixelId: { en: 'Snapchat Pixel ID', ar: 'معرف Snapchat Pixel' },
  tiktokPixelId: { en: 'TikTok Pixel ID', ar: 'معرف TikTok Pixel' },

  // Chat Widget
  aiAssistant: { en: 'AI Assistant', ar: 'المساعد الذكي' },
  chatWithAI: { en: 'Chat with AI', ar: 'تحدث مع المساعد' },
  typeMessage: { en: 'Type a message...', ar: 'اكتب رسالة...' },
  
  // Google Auth
  signInWithGoogle: { en: 'Continue with Google', ar: 'المتابعة باستخدام Google' },
  or: { en: 'OR', ar: 'أو' },

  // Footer
  disclaimerTitle: { en: 'Disclaimer', ar: 'تنبيه' },
  disclaimerText: { en: 'The site does not bear any responsibility for the accuracy, correctness, or reliability of the data displayed within it, and the use of the displayed content is the sole responsibility of the user.', ar: 'لا يتحمّل الموقع أي مسؤولية عن دقة أو صحة أو موثوقية البيانات المعروضة داخله، ويُعد استخدام المحتوى المعروض على مسؤولية المستخدم وحده.' },
  copyrightText: { en: 'All rights reserved | ai-guid.com', ar: 'كافة الحقوق محفوظة | ai-guid.com' },
  technicalSupport: { en: 'Technical Support', ar: 'الدعم الفني' },
  supportMessage: { en: 'For any technical assistance or inquiry about our services, we are happy to contact you via email:', ar: 'لأي مساعدة تقنية أو استفسار عن خدماتنا، يسعدنا تواصلك عبر البريد:' },
  
  // Support System
  support: { en: 'Support', ar: 'الدعم الفني' },
  openTicket: { en: 'Open Ticket', ar: 'فتح تذكرة' },
  myTickets: { en: 'My Tickets', ar: 'تذاكري' },
  ticketSubject: { en: 'Subject', ar: 'الموضوع' },
  ticketType: { en: 'Ticket Type', ar: 'نوع الطلب' },
  selectType: { en: 'Select Type', ar: 'اختر النوع' },
  technicalSupportType: { en: 'Technical Support', ar: 'دعم فني' },
  additionalService: { en: 'Request Additional Service', ar: 'طلب خدمة إضافية' },
  specialSubscription: { en: 'Request Special Subscription', ar: 'طلب اشتراك خاص' },
  message: { en: 'Message', ar: 'الرسالة' },
  submitTicket: { en: 'Submit Ticket', ar: 'إرسال التذكرة' },
  ticketStatus: { en: 'Status', ar: 'الحالة' },
  open: { en: 'Open', ar: 'مفتوحة' },
  closed: { en: 'Closed', ar: 'مغلقة' },
  answered: { en: 'Answered', ar: 'تم الرد' },
  noTickets: { en: 'No tickets found.', ar: 'لا توجد تذاكر.' },
  adminReply: { en: 'Admin Reply', ar: 'رد الإدارة' },
  typeReply: { en: 'Type a reply...', ar: 'اكتب رداً...' },
  send: { en: 'Send', ar: 'إرسال' },
  ticketCreated: { en: 'Ticket created successfully!', ar: 'تم إنشاء التذكرة بنجاح!' },
  manageTicketTypes: { en: 'Manage Ticket Types', ar: 'إدارة أنواع التذاكر' },
  addType: { en: 'Add Type', ar: 'إضافة نوع' },
  typePlaceholder: { en: 'Enter type name...', ar: 'أدخل اسم النوع...' },
  supportSettings: { en: 'Support Settings', ar: 'إعدادات الدعم' },
};