import jsPDF from 'jspdf';
import { Language } from '../types';

// Base64 encoded Cairo-Regular.ttf font to support Arabic characters in the PDF.
const cairoFontBase64 = 'AAEAAAASAQAABAAgR0RFRgBsBNsAAelEAAAAHkdQT1OhEGLMAAGB/AAAAGBHU1VCA8LPbQAAEqgAAABQT1MvMnesbQAABCgAAABgY21hcPdpIf4AABIIAAAGMmN2dCAAIgRsAAAFVAAAAARmcGdtUKea/gAABVgAAAJlZ2FzcAAAABAAAAeoAAAACGdseWZ2gUETAAAIiAAABNBnbHhjbXBsdW5kAAAAA2hlYWQyG6cWAAADLAAAADZoaGVhCBsDzwAACOwAAAAkaG10eAoAgUIAAAmQAAAAWGxvY2EAwAG0AAAIYAAAAHAmaxgAhALGAAB54AAAAxtwb3N0AAMAAAAAenwAAAEAAQAAB9D62F8PPPUACwQAAAAAANi5GAAAAADYuRj//gbiBEAEAAAAAAAABAAAAAAAAAAAAAAAgAAAAAAMAQAAAAMAAIAADAAEAAAAAAAAAAAAAAAAAAAAAAAQGoAZAyuAFwAAAAAAaAAAAAkAAAACAAAAAAADAAEAAgAAAC4ALgAIAAAAAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAZgBkAFUA0ALoIAAyAC4AAAUUABEBGgABAAAAAAQAAAAAAAAAAAAAAIAAAAAAAoAAMABAAAACgAFAAIAAwAEAAUALgBKAEwAUgBTAFcAXgBlAGsAbgB1AIIAiQCMAJ4AqgCxAMAAyADaAOsA9wEGASIBKwE2AUcBVQFeAY4BmwGrAbIBugHAAb4BywHWAd4B6AHwAgYCHAIoAjYCPgJMAlUAAAAFAAUACgANABQAFwAcACIAJQApACwALwAyADcAOgA/AEQARwBKAE0AUgBUAFcAWQBcAF8AYgBlAGgAaQBsAG8AcgB1AGAAcwCJAJgAogCrALYAvADIAAAAAAABAAAAAAMAAAADAAAAHAABAAAAAABGAAMAAQAAABwABAEAAAAOABoAAgABAAgAGQAnACgALQAxADUAOQA9AEEARgBLAE8AUwBXAFsAYwBoAGwAcQBzAHYAeQB6AHsAgQCEAIgAigCUAJYAmACgAKQAqwCtALUAuwC9AMUAzQDRANsA4QDkAOwA9AECARgBJgEyATgBRwFOAVoBYQFvAXgBeQGAAYgBjAGsAawBtAG4AcQBzAHUAdwB5AHsAfACBAIYAjACQAAAAAAAAAAAAEAAAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AGAAcwB0AHUAdgB3AHgAeQB6AHsAfAB9AH4AfwCAAIEAhgCEAIUAhgCHAIgAiQCKAIsAjACNAI4AjwCQAJEAkpCTAJQAlQCWAIQAlwCYAJoAmwCcAJ0Anhr/9gADAGYAagADAAEAAAAAAAAAAAAAAAAAPQBAAEIAQwBEAEUAaABsAG0AcgB0AHYAeAB6AHwAggCOAJQAogCwAMgA3gDyAQoBHAEwAToBSgFWAV4BiAGaAawBtAG6AcABvgHMAc4B3gHpAf4CAgISAiYCLgI+AkwCVQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAFUAVQBPAEcAUwBPAEcARwBAAD8AUgA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/AD8APwA/-';

export const exportTextToPdf = async (
    title: string,
    text: string,
    language: Language
) => {
    // FIX: Using inline styles instead of CSS classes ensures consistent styling when converting HTML to PDF with js-P-D-F.
    // The direction and text alignment are set dynamically based on the language.
    const htmlContent = `
        <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body { font-family: 'Cairo', sans-serif; }
                </style>
            </head>
            <body>
                <h1>${title}</h1>
                <div style="direction: ${language === Language.AR ? 'rtl' : 'ltr'}; text-align: ${language === Language.AR ? 'right' : 'left'};">${text}</div>
            </body>
        </html>
    `;

    const doc = new jsPDF();

    doc.addFileToVFS('Cairo-Regular.ttf', cairoFontBase64);
    doc.addFont('Cairo-Regular.ttf', 'Cairo', 'normal');
    doc.setFont('Cairo');

    // The `html` method is the modern and recommended way to render HTML content in jsPDF.
    // It offers better control and supports more complex layouts.
    doc.html(htmlContent, {
        callback: function (doc) {
            doc.save(`${title}.pdf`);
        },
        x: 10,
        y: 10,
        width: 190, // A4 width in mm is 210, leaving some margin
        windowWidth: 650 // A reasonable width for rendering
    });
};
