
import React, { useState, useMemo, useEffect, useRef } from 'react';
import { Loader2, Wand2, Send, Copy, Check, Printer, X, ArrowLeft, ArrowRight, File, MapPin, Sparkles, FileText, LayoutGrid, Search, Star, Settings2, Sliders, ChevronRight as ChevronRightIcon, Gavel, Shield, Building2, Users, Scale, Briefcase, AudioLines, Search as SearchIcon, Archive, ZoomIn, ZoomOut, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, AlertTriangle, Crown } from 'lucide-react';
import { useLanguage } from '../hooks/useLanguage';
import { useAuth } from '../hooks/useAuth';
import { useSiteSettings } from '../hooks/useSiteSettings';
import { Service, Translations, Language, Category } from '../types';
import { collection, getDocs, query, doc, updateDoc, increment, orderBy } from 'firebase/firestore';
import { db } from '../services/firebase';
import { runGemini } from '../services/geminiService';
import { iconMap } from '../constants';

interface DashboardPageProps {
    onNavigate: (view: 'dashboard' | 'admin' | 'profile' | 'subscriptions') => void;
}

const professionalOutputInstructionSystem = `أنت مساعد قانوني خبير ومحترف. مهمتك هي تنفيذ الطلب الذي يقدمه المستخدم بشكل مباشر وتقديم إجابة نهائية كاملة. لا تقم بتلخيص الطلب أو تكراره أو شرح ما ستفعله. ابدأ مباشرة في تنفيذ المهمة المطلوبة.

التعليمات الهامة:
- قم بتنظيم إجابتك باستخدام العناوين والنقاط والقوائم لجعلها سهلة القراءة والفهم.
- لا تستخدم أي وسوم HTML في إجابتك. قدم الرد كنص عادي منسق.
- أنهِ إجابتك **دائمًا** بالملاحظة التالية في سطر منفصل: "💡 ملاحظة: تم إنشاء هذا المستند بواسطة المساعد الذكي ويجب مراجعته من قبل متخصص."
`;

const professionalOutputInstructionSystemEN = `You are an expert and professional legal assistant. Your task is to directly execute the user's request and provide a complete, final answer. Do not summarize the request, repeat it, or explain what you are going to do. Begin executing the required task immediately.

IMPORTANT INSTRUCTIONS:
- Structure your response using headings, bullet points, and lists to make it easy to read and understand.
- Do not use any HTML tags in your response. Provide the response as formatted plain text.
- **Always** end your response with the following note on a new line: "💡 Note: This document was generated by the Smart Assistant and should be reviewed by a qualified professional."
`;


const stripHtml = (html: string) => html.replace(/<[^>]*>?/gm, '');

const DashboardPage: React.FC<DashboardPageProps> = ({ onNavigate }) => {
    const { t, language, dir } = useLanguage();
    const { currentUser } = useAuth();
    const { settings } = useSiteSettings();
    const [services, setServices] = useState<Service[]>([]);
    const [categories, setCategories] = useState<Category[]>([]);
    const [loadingServices, setLoadingServices] = useState(true);
    const [loadingCategories, setLoadingCategories] = useState(true);
    const [errorServices, setErrorServices] = useState<string | null>(null);
    const [selectedService, setSelectedService] = useState<Service | null>(null);
    
    const [formData, setFormData] = useState<Record<string, any>>({});
    const [prompt, setPrompt] = useState('');
    const [result, setResult] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [retryMessage, setRetryMessage] = useState('');
    const [isCopied, setIsCopied] = useState(false);
    const [fontSize, setFontSize] = useState(18);
    
    // Search and Filter States
    const [selectedCategory, setSelectedCategory] = useState<string>('all');
    const [searchQuery, setSearchQuery] = useState('');
    const [outputLanguage, setOutputLanguage] = useState<Language>(language);
    const [favorites, setFavorites] = useState<string[]>([]);
    const [outputLength, setOutputLength] = useState<'default' | 'short' | 'medium'>('default');
    
    // Pagination state
    const [currentPage, setCurrentPage] = useState(0);
    const SERVICES_PER_PAGE = 12;

    const [isExpanded, setIsExpanded] = useState(false);
    const [isOutputExpanded, setIsOutputExpanded] = useState(false);
    const [isResultModalOpen, setIsResultModalOpen] = useState(false);

    const handleToggleServices = () => {
        const nextState = !isExpanded;
        setIsExpanded(nextState);
        if (nextState) {
            setIsOutputExpanded(false);
        }
    };

    const handleToggleOutput = () => {
        const nextState = !isOutputExpanded;
        setIsOutputExpanded(nextState);
        if (nextState) {
            setIsExpanded(false);
        }
    };


    useEffect(() => {
        setOutputLanguage(language);
    }, [language]);
    
    // Reset page number when filters change
    useEffect(() => {
        setCurrentPage(0);
    }, [selectedCategory, searchQuery]);

    // Load favorites from local storage
    useEffect(() => {
        const storedFavs = localStorage.getItem('favoriteServices');
        if (storedFavs) {
            try {
                setFavorites(JSON.parse(storedFavs));
            } catch (e) {
                console.error("Failed to parse favorites", e);
            }
        }
    }, []);

    useEffect(() => {
        const fetchServices = async () => {
            setLoadingServices(true);
            setErrorServices(null);
            try {
                const servicesCollectionRef = collection(db, 'services');
                const servicesSnapshot = await getDocs(servicesCollectionRef);
                const servicesList = servicesSnapshot.docs.map(doc => ({ ...doc.data(), id: doc.id } as Service));
                
                servicesList.sort((a, b) => {
                    // Sort by Title EN to keep it consistent within categories
                    return (a.title.en || '').localeCompare(b.title.en || '');
                });

                setServices(servicesList);
            } catch (err) {
                console.error("Error fetching services: ", err);
                setErrorServices(t('fetchServicesError'));
            } finally {
                setLoadingServices(false);
            }
        };
        const fetchCategories = async () => {
            setLoadingCategories(true);
            try {
                const catRef = collection(db, 'service_categories');
                const q = query(catRef, orderBy('order'));
                const snapshot = await getDocs(q);
                // FIX: Spread doc.id to ensure the ID is available
                const cats = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id } as Category));
                setCategories(cats);
            } catch (e) {
                console.error("Failed to fetch categories", e);
            } finally {
                setLoadingCategories(false);
            }
        }
        fetchServices();
        fetchCategories();
    }, [t, language]);

    const filteredServices = useMemo(() => {
        let filtered = services;

        // 1. Filter by Category
        if (selectedCategory === 'favorites') {
            filtered = filtered.filter(s => favorites.includes(s.id));
        } else if (selectedCategory !== 'all') {
            filtered = filtered.filter(s => s.category === selectedCategory);
        }

        // 2. Filter by Search Query
        if (searchQuery.trim()) {
            const query = searchQuery.toLowerCase();
            filtered = filtered.filter(s => 
                (s.title.en && s.title.en.toLowerCase().includes(query)) || 
                (s.title.ar && s.title.ar.toLowerCase().includes(query)) ||
                (s.description.en && s.description.en.toLowerCase().includes(query)) ||
                (s.description.ar && s.description.ar.toLowerCase().includes(query))
            );
        }

        return filtered;
    }, [services, selectedCategory, searchQuery, favorites]);

    const sidebarCategories = useMemo(() => {
        const dynamicCategories = categories.map(cat => {
            const IconComponent = iconMap[cat.icon] || Gavel;
            return {
                id: cat.id,
                label: cat.title[language],
                icon: IconComponent,
                color: 'text-primary-600' // Unified color
            };
        });
    
        return [
            // Note: 'all' is handled specially in render
            { id: 'all', label: t('allCategories'), icon: LayoutGrid, color: 'text-gray-400' },
            { id: 'favorites', label: t('favorites'), icon: Star, color: 'text-primary-400' },
            ...dynamicCategories
        ];
    }, [categories, language, t]);
    

    const toggleFavorite = (e: React.MouseEvent, serviceId: string) => {
        e.stopPropagation(); // Prevent opening the service when clicking star
        const newFavs = favorites.includes(serviceId)
            ? favorites.filter(id => id !== serviceId)
            : [...favorites, serviceId];
        
        setFavorites(newFavs);
        localStorage.setItem('favoriteServices', JSON.stringify(newFavs));
    };

    const handleExecutePrompt = async () => {
        if (!prompt.trim()) return;

        if (currentUser && !currentUser.isAdmin && (currentUser.tokenBalance || 0) <= 0) {
            setResult(t('outOfTokens'));
            return;
        }

        setIsGenerating(true);
        setResult('');
        setRetryMessage('');

        const handleRetry = (attempt: number, maxRetries: number) => {
            const message = t('modelIsBusyRetrying').replace('${attempt}', String(attempt)).replace('${maxRetries}', String(maxRetries));
            setRetryMessage(message);
        };

        try {
            const userLocation = currentUser?.location;
            const locationContext = userLocation ? `\n\nCONTEXT: The user is located in ${userLocation}. Please answer based on the laws and regulations of ${userLocation} unless specified otherwise.` : '';
            
            let finalPrompt = prompt + locationContext;

            let geminiConfig: any = {};
            if (outputLength === 'short') {
                geminiConfig = { maxOutputTokens: 512, thinkingConfig: { thinkingBudget: 256 } };
            } else if (outputLength === 'medium') {
                geminiConfig = { maxOutputTokens: 2048, thinkingConfig: { thinkingBudget: 1024 } };
            }

            if (outputLanguage === Language.AR) {
                geminiConfig = { ...geminiConfig, systemInstruction: professionalOutputInstructionSystem };
            } else {
                finalPrompt += `\n\nIMPORTANT: Provide the response strictly in English language.`;
                geminiConfig = { ...geminiConfig, systemInstruction: professionalOutputInstructionSystemEN };
            }
            
            const response = await runGemini('gemini-2.5-flash', finalPrompt, undefined, handleRetry, geminiConfig);
            setResult(response.text);
            if (response.text) {
                setIsResultModalOpen(true);
            }

            if (currentUser && !currentUser.isAdmin) {
                const tokensConsumed = response.usageMetadata?.totalTokens || 0;
                if (tokensConsumed > 0) {
                    const userRef = doc(db, 'users', currentUser.uid);
                    await updateDoc(userRef, {
                        tokenBalance: increment(-tokensConsumed),
                        tokensUsed: increment(tokensConsumed)
                    });
                }
            }

        } catch (error) {
            let errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
            if (errorMessage.includes('QUOTA_EXHAUSTED')) {
                 errorMessage = t('quotaExhaustedMessage');
            }
            setResult(`${t('serviceSavedError')}: ${errorMessage}`);
        } finally {
            setIsGenerating(false);
            setRetryMessage('');
        }
    };

    const handleServiceClick = (service: Service) => {
        setSelectedService(service);
        setFormData({});
        setResult('');
    };

    const handleBackToServices = () => {
        setSelectedService(null);
    };
    
    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        if (type === 'file') {
            const files = (e.target as HTMLInputElement).files;
            setFormData(prev => ({ ...prev, [name]: files ? files[0] : null }));
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const handleServiceFormSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedService) return;

        if (currentUser && !currentUser.isAdmin && (currentUser.tokenBalance || 0) <= 0) {
            setResult(t('outOfTokens'));
            return;
        }
    
        setIsGenerating(true);
        setResult('');
        setRetryMessage('');
    
        const constructPromptForService = () => {
            if (!selectedService) return '';
            let prompt = `Service: ${selectedService.title.en}.\n`;
            for (const key in formData) {
                if (key.includes('file')) continue;
                const inputConfig = selectedService.formInputs.find(i => i.name === key);
                prompt += `${inputConfig?.label.en || key}: ${formData[key]}\n`;
            }
            const userLocation = currentUser?.location;
            if (userLocation) {
                prompt += `\nCONTEXT: The user is located in ${userLocation}. Apply the laws and regulations of ${userLocation}.`;
            }

            if (outputLanguage === Language.EN) {
                prompt += `\n\nIMPORTANT: The output must be in English language.`;
            }
            return prompt;
        };
    
        const promptText = constructPromptForService();
        const fileInput = selectedService.formInputs.find(i => i.type === 'file');
        const file = fileInput ? formData[fileInput.name] as File : undefined;
    
        const handleRetry = (attempt: number, maxRetries: number) => {
            const message = t('modelIsBusyRetrying').replace('${attempt}', String(attempt)).replace('${maxRetries}', String(maxRetries));
            setRetryMessage(message);
        };
    
        try {
            let geminiConfig = selectedService.geminiConfig || {};
            if (outputLength === 'short') {
                geminiConfig = { ...geminiConfig, maxOutputTokens: 512, thinkingConfig: { thinkingBudget: 256 } };
            } else if (outputLength === 'medium') {
                geminiConfig = { ...geminiConfig, maxOutputTokens: 2048, thinkingConfig: { thinkingBudget: 1024 } };
            }

            let finalSystemInstruction = '';
            const serviceSystemInstruction = selectedService.systemInstruction?.[outputLanguage] || selectedService.systemInstruction?.[language] || '';
            
            if (outputLanguage === Language.AR) {
                finalSystemInstruction = `${serviceSystemInstruction}\n\n---\n\n${professionalOutputInstructionSystem}`.trim();
            } else {
                finalSystemInstruction = `${serviceSystemInstruction}\n\n---\n\n${professionalOutputInstructionSystemEN}`.trim();
            }
            
            geminiConfig = { ...geminiConfig, systemInstruction: finalSystemInstruction };

            // ---------------------------------------------------------------------------
            // AUTO-FIX: Check for deprecated models
            // ---------------------------------------------------------------------------
            let modelToUse = selectedService.geminiModel;
            const validModels = ['gemini-2.5-flash', 'gemini-3-pro-preview'];
            
            if (
                !modelToUse ||
                modelToUse.includes('1.5') || 
                modelToUse.includes('gemini-pro') ||
                modelToUse.includes('latest') ||
                (!modelToUse.includes('2.5') && !modelToUse.includes('3-pro') && !modelToUse.includes('veo') && !modelToUse.includes('imagen'))
            ) {
                console.warn(`[Dashboard] Deprecated model detected: ${modelToUse}. Switching to gemini-2.5-flash.`);
                modelToUse = 'gemini-2.5-flash';
            }

            const response = await runGemini(modelToUse, promptText, file, handleRetry, geminiConfig);
            setResult(response.text);

            const isSuccess = !!response.text;
    
            if (isSuccess) {
                setIsResultModalOpen(true);
                if (selectedService?.id) {
                    try {
                        const serviceRef = doc(db, 'services', selectedService.id);
                        await updateDoc(serviceRef, {
                            usageCount: increment(1)
                        });
                    } catch (err) {
                        console.error("Failed to update service usage count:", err);
                    }
                }

                if (currentUser && !currentUser.isAdmin) {
                    const tokensConsumed = response.usageMetadata?.totalTokens || 0;
                     if (tokensConsumed > 0) {
                        const userRef = doc(db, 'users', currentUser.uid);
                        await updateDoc(userRef, {
                            tokenBalance: increment(-tokensConsumed),
                            tokensUsed: increment(tokensConsumed)
                        });
                    }
                }
            }
        } catch (error) {
            let errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
            if (errorMessage.includes('QUOTA_EXHAUSTED')) {
                 errorMessage = t('quotaExhaustedMessage');
            }
            setResult(`${t('serviceSavedError')}: ${errorMessage}`);
        } finally {
            setIsGenerating(false);
            setRetryMessage('');
        }
    };

    const copyToClipboard = () => {
        if (result) {
            navigator.clipboard.writeText(stripHtml(result));
            setIsCopied(true);
            setTimeout(() => setIsCopied(false), 2000);
        }
    };

    const handlePrint = () => {
        const printWindow = window.open('', '_blank');
        if (printWindow) {
            const contentToPrint = result.trim().startsWith('<section')
                ? result
                : `<pre style="font-family: Calibri, sans-serif;">${result}</pre>`;
            printWindow.document.write(`
              <html>
                <head>
                  <title>Print Result</title>
                  <style>
                    @import url('https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;700&display=swap');
                    body { font-family: 'Calibri', 'Noto Naskh+Arabic', 'Tajawal', sans-serif; direction: ${language === 'ar' ? 'rtl' : 'ltr'}; padding: 20px; }
                    pre { white-space: pre-wrap; word-wrap: break-word; font-size: 14px; }
                  </style>
                </head>
                <body>${contentToPrint}</body>
              </html>
            `);
            printWindow.document.close();
            printWindow.focus();
            printWindow.print();
            printWindow.close();
        }
    };

    const handleClear = () => {
        setResult('');
    };

    const handleZoomIn = () => setFontSize(s => Math.min(s + 1, 32));
    const handleZoomOut = () => setFontSize(s => Math.max(s - 1, 8));

    const renderOutputLanguageSelector = (showLabel = true) => (
        <div className="flex flex-col sm:flex-row items-center gap-3 flex-shrink-0">
            <div className="flex items-center gap-2">
                {showLabel && <span className="text-sm font-medium text-gray-700 dark:text-gray-300 hidden sm:inline">{t('outputLanguage')}</span>}
                <div className="flex bg-gray-200 dark:bg-dark-card-bg rounded-lg p-1 border dark:border-dark-border">
                    <button
                        type="button"
                        onClick={() => setOutputLanguage(Language.AR)}
                        className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${outputLanguage === Language.AR ? 'bg-white dark:bg-primary-900/50 shadow text-primary-600 dark:text-primary-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
                    >
                        {t('arabic')}
                    </button>
                    <button
                        type="button"
                        onClick={() => setOutputLanguage(Language.EN)}
                        className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${outputLanguage === Language.EN ? 'bg-white dark:bg-primary-900/50 shadow text-primary-600 dark:text-primary-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
                    >
                        {t('english')}
                    </button>
                </div>
            </div>
        </div>
    );

    const renderOutputLengthSelector = (showLabel = true) => (
         <div className="flex items-center gap-2">
            {showLabel && <span className="text-sm font-medium text-gray-700 dark:text-gray-300 hidden sm:inline">{t('outputLength')}</span>}
            <div className="flex bg-gray-200 dark:bg-dark-card-bg rounded-lg p-1 border dark:border-dark-border">
                <button
                    type="button"
                    onClick={() => setOutputLength('short')}
                    className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${outputLength === 'short' ? 'bg-white dark:bg-primary-900/50 shadow text-primary-600 dark:text-primary-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
                >
                    {t('short')}
                </button>
                <button
                    type="button"
                    onClick={() => setOutputLength('medium')}
                    className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${outputLength === 'medium' ? 'bg-white dark:bg-primary-900/50 shadow text-primary-600 dark:text-primary-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
                >
                    {t('medium')}
                </button>
                 <button
                    type="button"
                    onClick={() => setOutputLength('default')}
                    className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${outputLength === 'default' ? 'bg-white dark:bg-primary-900/50 shadow text-primary-600 dark:text-primary-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
                >
                    {t('default')}
                </button>
            </div>
        </div>
    );
    
    // -------------------- FRAME 1: IDENTITY & NAVIGATION (SIDEBAR) --------------------
    const renderSidebar = () => {
        const siteName = settings?.siteName[language] || (language === 'ar' ? 'المساعد الذكي' : 'Smart Assistant');
        const siteSubtitle = settings?.siteSubtitle[language] || (language === 'ar' ? 'للمحاماة والاستشارات القانونية' : 'For Law and Legal Consulting');

        return (
        <div className="flex flex-col h-full rounded-2xl bg-[#1c1c1e] shadow-lg border border-white/10 overflow-hidden w-full min-w-0">
            {/* Header */}
            <div className="h-auto py-6 min-h-[5rem] flex flex-col justify-center px-6 bg-gradient-to-r from-primary-700 to-primary-600 border-b border-primary-600/30 shrink-0 shadow-sm text-center">
                 <div className="flex flex-col items-center min-w-0 overflow-hidden text-center w-full">
                    <h2 className="text-2xl font-black tracking-tight leading-none text-white mb-2 font-cairo w-full">
                        {siteName}
                    </h2>
                    <p className="text-[10px] text-primary-100 font-bold tracking-wide opacity-90 font-cairo w-full">
                        {siteSubtitle}
                    </p>
                </div>
            </div>

            {/* Search */}
            <div className="p-4 border-b border-white/10">
                 <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 rtl:right-3 rtl:left-auto" size={16} />
                    <input
                        type="text"
                        placeholder={t('searchServicePlaceholder')}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full py-2 pl-10 pr-4 rtl:pr-10 rtl:pl-4 rounded-xl bg-white/5 text-white border border-white/10 focus:ring-2 focus:ring-primary-500 focus:outline-none text-sm transition-all placeholder-gray-500"
                    />
                </div>
            </div>

            {/* Categories Navigation */}
            <div className="flex-grow overflow-y-auto custom-scrollbar p-3 space-y-2 w-full min-w-0">
                {loadingCategories ? (
                    <div className="flex justify-center p-4"><Loader2 className="animate-spin text-primary-500" /></div>
                ) : sidebarCategories.map(cat => {
                    const isActive = selectedCategory === cat.id;
                    
                    // SPECIAL HANDLING FOR 'all' (The "Smart Assistant" button)
                    if (cat.id === 'all') {
                        return (
                            <button
                                key={cat.id}
                                onClick={() => {
                                    setSelectedCategory(cat.id);
                                    setSelectedService(null);
                                }}
                                className={`relative overflow-hidden w-full flex items-center gap-3 px-4 py-4 rounded-xl transition-all duration-300 group ${
                                    isActive 
                                    ? 'bg-gradient-to-br from-[#8B0000] via-[#A52A2A] to-[#8B0000] border-red-400/50 shadow-[0_0_15px_rgba(139,0,0,0.5)] scale-[1.02]' 
                                    : 'bg-gradient-to-br from-[#581c1c] via-[#7f2828] to-[#581c1c] border-red-900/30 hover:border-red-500/50 hover:shadow-lg'
                                } border`}
                            >
                                {/* Background Pattern */}
                                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10"></div>
                                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full group-hover:animate-shimmer"></div>

                                {/* Icon Container */}
                                <div className={`flex-shrink-0 p-2.5 rounded-lg ${isActive ? 'bg-white/20 text-white' : 'bg-black/20 text-red-200'} backdrop-blur-sm shadow-inner border border-white/10`}>
                                    {/* Animated Icon: Sparkles with pulse effect and Gold color */}
                                    <Sparkles size={24} className="animate-pulse text-yellow-300" fill={isActive ? "#FDE047" : "none"} />
                                </div>

                                {/* Text Content */}
                                <div className="flex flex-col items-start text-right rtl:text-right ltr:text-left flex-grow min-w-0">
                                    <span className="text-white font-black text-lg leading-none mb-1.5 font-cairo truncate w-full drop-shadow-sm">
                                        المساعد الذكي
                                    </span>
                                    <span className="text-red-100/80 text-[10px] font-medium truncate w-full font-cairo leading-tight">
                                        للمحاماة والاستشارات القانونية
                                    </span>
                                </div>
                                
                                {/* Active Indicator */}
                                {isActive && (
                                    <div className="absolute left-0 top-0 bottom-0 w-1 bg-white/50 shadow-[0_0_10px_white]"></div>
                                )}
                            </button>
                        );
                    }

                    const IconComponent = cat.icon;
                    let buttonClasses = `font-cairo w-full flex items-center justify-between gap-3 px-4 py-3 rounded-xl text-base font-bold transition-all duration-200 group`;
                
                    if (isActive) {
                        buttonClasses += ' bg-gradient-to-r from-primary-600 to-primary-500 text-white shadow-md';
                    } else {
                        buttonClasses += ' text-gray-300 hover:bg-white/5';
                    }

                    return (
                        <button
                            key={cat.id}
                            onClick={() => {
                                setSelectedCategory(cat.id);
                                setSelectedService(null);
                            }}
                            className={buttonClasses}
                        >
                            {language === 'ar' ? (
                                <>
                                    <div className="w-4">{isActive && <ArrowLeft size={16} />}</div>
                                    <span className="flex-grow text-right">{cat.label}</span>
                                    <div className={`p-2 rounded-lg transition-colors duration-200 ${
                                        isActive ? 'bg-white/20' : 'bg-white/5'
                                    }`}>
                                        <IconComponent size={20} className={
                                            isActive ? 'text-white' : 'text-primary-400'
                                        } />
                                    </div>
                                </>
                            ) : (
                                <>
                                    <div className={`p-2 rounded-lg transition-colors duration-200 ${
                                        isActive ? 'bg-white/20' : 'bg-white/5'
                                    }`}>
                                        <IconComponent size={20} className={
                                            isActive ? 'text-white' : 'text-primary-400'
                                        } />
                                    </div>
                                    <span className="flex-grow text-left">{cat.label}</span>
                                    <div className="w-4">{isActive && <ChevronRightIcon size={16} />}</div>
                                </>
                            )}
                        </button>
                    )
                })}
            </div>
        </div>
        );
    };

    // -------------------- FRAME 2: SERVICES & INPUT (MIDDLE) --------------------
    const renderMainContent = () => {
        const totalPages = Math.ceil(filteredServices.length / SERVICES_PER_PAGE);
        const paginatedServices = filteredServices.slice(
            currentPage * SERVICES_PER_PAGE,
            (currentPage + 1) * SERVICES_PER_PAGE
        );

        return (
            <div className="flex flex-col h-full rounded-2xl bg-gray-50 dark:bg-dark-card-bg border border-gray-200 dark:border-dark-border shadow-lg overflow-hidden relative w-full min-w-0">
                 {/* Header for Main Content */}
                 <div className="h-16 flex items-center px-6 bg-gradient-to-r from-primary-700 to-primary-600 dark:from-primary-900 dark:to-primary-800 border-b border-primary-600 dark:border-dark-border text-white shrink-0 justify-between shadow-sm relative z-10">
                    {selectedService ? (
                        <div className="flex items-center gap-3 w-full">
                             <button onClick={handleBackToServices} className="p-2 rounded-full hover:bg-white/20 transition-colors text-white">
                                {language === 'ar' ? <ArrowRight size={20} /> : <ArrowLeft size={20} />}
                            </button>
                            <div>
                                 <h3 className="font-cairo font-bold text-white text-sm leading-tight">{selectedService.title[language]}</h3>
                            </div>
                        </div>
                    ) : (
                        <div className="flex items-center justify-between w-full">
                            <h3 className="font-cairo font-bold text-white text-lg">
                                {selectedCategory === 'all' ? (language === 'ar' ? 'المساعد الذكي' : 'Smart Assistant') : sidebarCategories.find(c => c.id === selectedCategory)?.label}
                            </h3>
                            <button
                                onClick={handleToggleServices}
                                className="p-2 rounded-full hover:bg-white/20 transition-colors text-white"
                                title={isExpanded ? t('collapse') : t('expand')}
                            >
                                {dir === 'rtl' ? (
                                    isExpanded ? <PanelLeftClose size={20} /> : <PanelLeftOpen size={20} />
                                ) : (
                                    isExpanded ? <PanelRightOpen size={20} /> : <PanelRightClose size={20} />
                                )}
                            </button>
                        </div>
                    )}
                 </div>

                 <div className="flex-grow overflow-y-auto custom-scrollbar p-4 w-full min-w-0">
                     {selectedService ? (
                         /* Active Service Form */
                         <form onSubmit={handleServiceFormSubmit} className="space-y-5 animate-fade-in-up">
                             <div className="p-4 bg-primary-50 dark:bg-primary-900/10 rounded-xl border border-primary-100 dark:border-primary-800/30 text-sm text-primary-800 dark:text-primary-300">
                                 {selectedService.description[language]}
                             </div>
                             
                             <div className="space-y-4">
                                 {selectedService.formInputs.map(input => (
                                     <div key={input.name}>
                                         <label className="block text-sm font-bold text-slate-700 dark:text-gray-300 mb-2 uppercase tracking-wide">{input.label[language]}</label>
                                         {input.type === 'textarea' && <textarea name={input.name} onChange={handleInputChange} rows={4} className="w-full p-3 text-base border border-gray-200 dark:border-dark-border rounded-xl bg-white dark:bg-dark-bg text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none shadow-sm" />}
                                         {input.type === 'text' && <input type="text" name={input.name} onChange={handleInputChange} className="w-full p-3 text-base border border-gray-200 dark:border-dark-border rounded-xl bg-white dark:bg-dark-bg text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none shadow-sm" />}
                                         {input.type === 'date' && <input type="date" name={input.name} onChange={handleInputChange} className="w-full p-3 text-base border border-gray-200 dark:border-dark-border rounded-xl bg-white dark:bg-dark-bg text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none shadow-sm" />}
                                         {input.type === 'select' && (
                                             <select name={input.name} onChange={handleInputChange} className="w-full p-3 text-base border border-gray-200 dark:border-dark-border rounded-xl bg-white dark:bg-dark-bg text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none shadow-sm">
                                                 <option value="">{`Select ${input.label[language]}`}</option>
                                                 {input.options?.map(opt => <option key={opt.value} value={opt.value}>{opt.label[language]}</option>)}
                                             </select>
                                         )}
                                         {input.type === 'file' && (
                                             <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 dark:border-dark-border border-dashed rounded-xl bg-white dark:bg-dark-bg hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors group cursor-pointer relative">
                                                 <input id={input.name} name={input.name} type="file" className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" onChange={handleInputChange} />
                                                 <div className="space-y-1 text-center">
                                                     <File className="mx-auto h-10 w-10 text-gray-400 group-hover:text-primary-500 transition-colors"/>
                                                     <div className="flex text-xs text-gray-600 dark:text-gray-400 justify-center">
                                                         <span className="font-bold text-primary-600 dark:text-primary-400">{t('uploadFile')}</span>
                                                     </div>
                                                     <p className="text-[10px] text-gray-500 dark:text-gray-500">{formData[input.name] ? (formData[input.name] as File).name : t('noFileSelected')}</p>
                                                 </div>
                                             </div>
                                         )}
                                     </div>
                                 ))}
                             </div>
                             
                             <div className="sticky bottom-0 bg-gray-50 dark:bg-dark-card-bg pt-4 pb-2">
                                <div className="flex flex-col md:flex-row items-center justify-between gap-3">
                                    <button type="submit" disabled={isGenerating} className="w-full md:w-auto flex-grow bg-primary-600 text-white font-bold py-3 px-4 rounded-xl hover:bg-primary-700 disabled:bg-primary-400 disabled:cursor-not-allowed flex items-center justify-center gap-2 transition-colors shadow-lg shadow-primary-600/20 transform active:scale-95">
                                        {isGenerating && <Loader2 className="animate-spin" size={20} />}
                                        {t('executeTask')}
                                    </button>
                                    <div className="flex items-center gap-3 w-full md:w-auto">
                                        {renderOutputLengthSelector(false)}
                                        {renderOutputLanguageSelector(false)}
                                    </div>
                                </div>
                             </div>
                         </form>
                     ) : (
                         /* Services Grid */
                         <>
                            {loadingServices ? (
                                <div className="text-center p-12"><Loader2 className="animate-spin inline-block text-primary-500" size={32} /></div>
                            ) : errorServices ? (
                                <div className="flex flex-col items-center justify-center h-full text-center p-8">
                                    <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-full mb-4">
                                        <AlertTriangle size={32} className="text-red-500" />
                                    </div>
                                    <p className="text-red-500 font-medium mb-2">{errorServices}</p>
                                    <button onClick={() => window.location.reload()} className="text-sm text-gray-500 underline hover:text-gray-700">Retry</button>
                                </div>
                            ) : filteredServices.length === 0 ? (
                                <div className="flex flex-col items-center justify-center h-full text-center p-8 opacity-50">
                                    <div className="bg-gray-200 dark:bg-dark-bg p-4 rounded-full mb-4">
                                        <Search size={32} className="text-gray-400" />
                                    </div>
                                    <p className="text-gray-500 font-medium">{t('noServicesFound')}</p>
                                </div>
                            ) : (
                                <>
                                    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5 pb-4">
                                        {paginatedServices.map(service => {
                                            const Icon = iconMap[service.icon] || FileText;
                                            const isFav = favorites.includes(service.id);
                                            
                                            return (
                                                <button
                                                    key={service.id}
                                                    onClick={() => handleServiceClick(service)}
                                                    className="group relative flex flex-col p-5 bg-white dark:bg-dark-bg rounded-2xl shadow-md hover:shadow-xl hover:-translate-y-1 dark:shadow-none border border-gray-200 dark:border-dark-border transition-all duration-300 h-auto min-h-[160px] overflow-hidden text-right rtl:text-right ltr:text-left ring-1 ring-transparent hover:ring-primary-500/50 dark:hover:ring-primary-400/50"
                                                >
                                                    <div className="flex items-start justify-between w-full mb-4">
                                                        <div className="p-1 text-gray-300 hover:text-primary-400 transition-colors" 
                                                             onClick={(e) => toggleFavorite(e, service.id)}>
                                                            <Star size={18} fill={isFav ? "currentColor" : "none"} className={isFav ? "text-primary-400" : "text-gray-300"} />
                                                        </div>
                                                        
                                                        <div className={`p-2.5 rounded-xl transition-transform duration-300 group-hover:scale-110 bg-primary-50 dark:bg-primary-900/20 text-primary-600 dark:text-primary-400`}>
                                                            <Icon size={24} strokeWidth={1.5} />
                                                        </div>
                                                    </div>

                                                    <div className="flex flex-col justify-between flex-grow w-full">
                                                        <div>
                                                            <h3 className="font-cairo text-base font-bold text-gray-900 dark:text-white mb-2 leading-snug">
                                                                {service.title[language] || service.title['en']}
                                                            </h3>
                                                            <p className="text-xs text-gray-500 dark:text-gray-400 line-clamp-2 leading-relaxed font-medium opacity-80">
                                                                {service.description[language] || service.description['en']}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </button>
                                            );
                                        })}
                                    </div>
                                    {totalPages > 1 && (
                                        <div className="mt-6 flex justify-center items-center gap-4">
                                            <button
                                                onClick={() => setCurrentPage(p => Math.max(0, p - 1))}
                                                disabled={currentPage === 0}
                                                className="p-2 rounded-full bg-gray-400 dark:bg-gray-600 text-white hover:bg-gray-50 dark:hover:bg-gray-700 disabled:bg-gray-300 dark:disabled:bg-gray-500 disabled:cursor-not-allowed transition-colors"
                                                aria-label={language === 'ar' ? 'الصفحة السابقة' : 'Previous Page'}
                                            >
                                                {language === 'ar' ? <ArrowRight size={20} /> : <ArrowLeft size={20} />}
                                            </button>
                                            <span className="text-sm font-medium text-gray-600 dark:text-gray-400">
                                                {language === 'ar' ? `صفحة ${currentPage + 1} من ${totalPages}` : `Page ${currentPage + 1} of ${totalPages}`}
                                            </span>
                                            <button
                                                onClick={() => setCurrentPage(p => Math.min(totalPages - 1, p + 1))}
                                                disabled={currentPage >= totalPages - 1}
                                                className="p-2 rounded-full bg-gray-400 dark:bg-gray-600 text-white hover:bg-gray-50 dark:hover:bg-gray-700 disabled:bg-gray-300 dark:disabled:bg-gray-500 disabled:cursor-not-allowed transition-colors"
                                                aria-label={language === 'ar' ? 'الصفحة التالية' : 'Next Page'}
                                            >
                                                {language === 'ar' ? <ArrowLeft size={20} /> : <ArrowRight size={20} />}
                                            </button>
                                        </div>
                                    )}
                                </>
                            )}
                         </>
                     )}
                 </div>
            </div>
        )
    };

    // -------------------- FRAME 3: OUTPUT & CHAT (LEFT) --------------------
    const renderOutputPanel = () => (
        <div className="flex flex-col h-full rounded-2xl bg-[#fcfaf6] dark:bg-dark-card-bg border border-gray-200 dark:border-dark-border shadow-lg overflow-hidden w-full min-w-0">
             <div className="h-16 flex items-center px-4 bg-gradient-to-r from-primary-700 to-primary-600 dark:from-primary-900 dark:to-primary-800 border-b border-primary-600 dark:border-dark-border shrink-0 justify-between shadow-sm relative z-10">
                <h3 className="font-bold text-sm text-white flex items-center gap-2">
                    <Sparkles size={16} className="text-yellow-200"/>
                    {t('results')}
                </h3>
                <div className="flex items-center gap-1">
                    <button
                        onClick={handleToggleOutput}
                        className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"
                        title={isOutputExpanded ? t('collapse') : t('expand')}
                    >
                        {dir === 'rtl' ? (
                            isOutputExpanded ? <PanelRightOpen size={16} /> : <PanelRightClose size={16} />
                        ) : (
                            isOutputExpanded ? <PanelLeftOpen size={16} /> : <PanelLeftClose size={16} />
                        )}
                    </button>
                    <div className="w-px h-4 bg-white/20 mx-1"></div>
                    <button onClick={copyToClipboard} title={t('copy')} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors">{isCopied ? <Check size={16} className="text-white"/> : <Copy size={16} />}</button>
                    <button onClick={handlePrint} title={t('print')} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"><Printer size={16} /></button>
                    
                    <div className="w-px h-4 bg-white/20 mx-1"></div>
                    
                    <button onClick={handleZoomOut} title={language === 'ar' ? 'تصغير' : 'Zoom Out'} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"><ZoomOut size={16} /></button>
                    <button onClick={handleZoomIn} title={language === 'ar' ? 'تكبير' : 'Zoom In'} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"><ZoomIn size={16} /></button>
                    
                    <div className="w-px h-4 bg-white/20 mx-1"></div>

                    <button onClick={handleClear} title={t('cancel')} className="p-1.5 rounded text-red-300 hover:bg-white/10 hover:text-red-400 transition-colors"><X size={16} /></button>
                </div>
             </div>

             {/* Output Content */}
             <div className="flex-grow overflow-auto custom-scrollbar relative p-4 w-full min-w-0">
                {isGenerating ? (
                    <div className="flex flex-col items-center justify-center h-full">
                        <div className="relative">
                            <div className="absolute inset-0 bg-primary-200 rounded-full opacity-20 animate-ping"></div>
                            <Loader2 className="animate-spin text-primary-600 relative z-10" size={40} />
                        </div>
                        <p className="text-gray-500 text-center font-medium mt-4 animate-pulse">{retryMessage || t('generatingResponse')}</p>
                    </div>
                ) : result ? (
                    <div className="max-w-none w-full min-w-0">
                        {result.trim().startsWith('<section') ? (
                            <div style={{ fontSize: `${fontSize}px` }}>
                                <div dangerouslySetInnerHTML={{ __html: result }} />
                            </div>
                        ) : (
                             <pre 
                                className="whitespace-pre-wrap leading-loose text-left rtl:text-right bg-transparent p-0 m-0 text-gray-800 dark:text-gray-200"
                                style={{ fontSize: `${fontSize}px`, fontFamily: 'Calibri, Tajawal, sans-serif' }}
                            >
                                {result}
                            </pre>
                        )}
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center h-full text-center opacity-40">
                        <div className="w-20 h-20 bg-gray-100 dark:bg-dark-bg rounded-full flex items-center justify-center mb-4">
                            <Sparkles size={36} className="text-gray-400"/>
                        </div>
                        <p className="text-gray-400 font-medium text-sm max-w-[200px]">{t('resultPlaceholder')}</p>
                    </div>
                )}
             </div>

             {/* Prompt Input Area */}
             <div className="p-4 bg-gray-50 dark:bg-dark-card-bg border-t border-gray-200 dark:border-dark-border">
                <div className="relative">
                    <textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder={t('typeYourRequest')}
                        className="w-full h-24 p-3 ltr:pl-3 rtl:pr-3 resize-none border border-gray-300 dark:border-dark-border rounded-xl bg-white dark:bg-dark-bg text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:outline-none placeholder-gray-500 dark:placeholder-gray-500 text-sm shadow-inner"
                        dir={dir}
                    />
                    <button
                        onClick={handleExecutePrompt}
                        disabled={isGenerating || !prompt.trim()}
                        className="absolute bottom-3 ltr:right-3 rtl:left-3 w-9 h-9 rounded-lg bg-primary-600 text-white flex items-center justify-center hover:bg-primary-500 disabled:bg-gray-400 dark:disabled:bg-gray-600 transition-colors"
                    >
                        {isGenerating ? <Loader2 className="animate-spin" size={20} /> : <Wand2 size={20}/>}
                    </button>
                </div>
                <p className="text-center text-[10px] text-gray-400 dark:text-gray-500 mt-2 font-medium tracking-wide">
                    {t('poweredByAI')}
                </p>
            </div>
        </div>
    );
    
    const renderResultModal = () => (
        <div className="fixed inset-0 bg-black bg-opacity-60 z-50 flex justify-center items-center p-4 lg:hidden">
            <div className="bg-white dark:bg-dark-bg rounded-2xl shadow-xl w-full max-w-xl flex flex-col max-h-[90vh]">
                <div className="h-16 flex items-center px-4 bg-gradient-to-r from-primary-700 to-primary-600 dark:from-primary-900 dark:to-primary-800 border-b border-primary-600 dark:border-dark-border shrink-0 justify-between shadow-sm relative z-10">
                    <h3 className="font-bold text-sm text-white flex items-center gap-2">
                        <Sparkles size={16} className="text-yellow-200"/>
                        {t('results')}
                    </h3>
                    <div className="flex items-center gap-1">
                        <button onClick={copyToClipboard} title={t('copy')} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors">{isCopied ? <Check size={16} className="text-white"/> : <Copy size={16} />}</button>
                        <button onClick={handlePrint} title={t('print')} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"><Printer size={16} /></button>
                        <div className="w-px h-4 bg-white/20 mx-1"></div>
                        <button onClick={handleZoomOut} title={language === 'ar' ? 'تصغير' : 'Zoom Out'} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"><ZoomOut size={16} /></button>
                        <button onClick={handleZoomIn} title={language === 'ar' ? 'تكبير' : 'Zoom In'} className="p-1.5 rounded text-primary-100 hover:bg-white/10 transition-colors"><ZoomIn size={16} /></button>
                        <div className="w-px h-4 bg-white/20 mx-1"></div>
                        <button onClick={() => { setIsResultModalOpen(false); }} title={t('cancel')} className="p-1.5 rounded text-red-300 hover:bg-white/10 hover:text-red-400 transition-colors"><X size={16} /></button>
                    </div>
                </div>

                <div className="flex-grow overflow-y-auto custom-scrollbar bg-[#fcfaf6] dark:bg-dark-bg relative p-4">
                    {isGenerating ? (
                        <div className="flex flex-col items-center justify-center h-full">
                           <Loader2 className="animate-spin text-primary-600" size={40} />
                            <p className="text-gray-500 text-center font-medium mt-4">{retryMessage || t('generatingResponse')}</p>
                        </div>
                    ) : result ? (
                        <div className="max-w-none">
                            {result.trim().startsWith('<section') ? (
                                <div style={{ fontSize: `${fontSize}px` }}>
                                    <div dangerouslySetInnerHTML={{ __html: result }} />
                                </div>
                            ) : (
                                <pre 
                                    className="whitespace-pre-wrap leading-loose text-left rtl:text-right bg-transparent p-0 m-0 text-gray-800 dark:text-gray-200"
                                    style={{ fontSize: `${fontSize}px`, fontFamily: 'Calibri, Tajawal, sans-serif' }}
                                >
                                    {result}
                                </pre>
                            )}
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-full text-center opacity-40">
                            <p className="text-gray-400 font-medium text-sm">{t('resultPlaceholder')}</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );

    return (
        <div className="flex-grow bg-light-bg dark:bg-dark-bg py-4 sm:py-6 lg:py-8">
             <div className="w-[90%] mx-auto h-full">
                 <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 h-full">
                    <div className="lg:col-span-1 h-full w-full min-w-0">{renderSidebar()}</div>
                    <div className={`${
                        isOutputExpanded
                            ? 'hidden'
                            : isExpanded
                            ? 'lg:col-span-3'
                            : 'lg:col-span-2'
                    } h-full transition-all duration-300 w-full min-w-0`}>
                        {renderMainContent()}
                    </div>
                    <div className={`${
                        isExpanded
                            ? 'hidden'
                            : isOutputExpanded
                            ? 'lg:col-span-3'
                            : 'lg:col-span-1'
                    } h-full transition-all duration-300 hidden lg:flex w-full min-w-0`}>
                        {renderOutputPanel()}
                    </div>
                </div>
            </div>
            {isResultModalOpen && renderResultModal()}
        </div>
    );
};

export default DashboardPage;
